### ISSUE TITLE
Hiding widget

### ISSUE THREAD

**Issue by mtangoo** [kartik-v/yii2-widget-select2#1]
How do I hide widget? Simple JQuery code below does not work.
Google only gives how to hide dropdown. I want to hide whole widget in some case
```javascript
$("#widget_id").hide() // show(false) does not work
```

**Comment by kartik-v** [comment]
Just add it to the widget options via CSS for example.
```php
echo Select2::widget([
   'name'=>'kv',
   'data'=>$list,
   'options'=>['style'=>'display:none'] // will hide the widget
]);
```

**Comment by ossse** [comment]
how to hide by javascript?

**Comment by ossse** [comment]
Hi @kartik-v , that is not working on me to hide select2

**Comment by aleksbelic** [comment]
Doesn't work for me either.
