### ISSUE TITLE
pluginEvents

### ISSUE THREAD

**Issue by wokster** [kartik-v/yii2-widget-select2#10]
That is in your docs:
```php
pluginEvents = [
    "change" => "function() { log('change'); }",
    "select2-open" => "function() { log('open'); }",
    "select2-opening" => "function() { log('select2-opening'); }",
    "select2-close" => "function() { log('close'); }",
    "select2-highlight" => "function() { log('highlight'); }",
    "select2-removing" => "function() { log('removing'); }",
    "select2-removed" => "function() { log('removed'); }",
    "select2-loaded" => "function() { log('loaded'); }",
    "select2-focus" => "function() { log('focus'); }",
    "select2-blur" => "function() { log('blur'); }",
];
```

it is not working

**Comment by kartik-v** [comment]
Related to #9. Please don't create duplicate issues.

The pluginEvents configured as above does work. You need to debug and check what's happening on your client.

**Comment by efisiobova** [comment]
Using pluginEvents inside a FormGrid seems not working. 
No messages are showed on the console in Chrome. (I tryed even with alert instead of log)
What am I doing wrong?
thanks



echo FormGrid::widget([
    'model' => $model,
    'form' => $form,
    'autoGenerateColumns'=>false,
    'rows'=>[   
        [
        'columns'=>2,
        'attributes' => [
            'tipoOperazione'=>['type'=> Form::INPUT_WIDGET, 'widgetClass'=>'\kartik\widgets\Select2',  
                'options'=>['data'=>$datac,],  
                'pluginEvents' => [
                    "change" => "function() { log('change'); }",
                    "select2:open" => "function() { log('open'); }",
                    "select2:opening" => "function() { log('select2-opening'); }",
                    "select2:close" => "function() { log('close'); }",
                    "select2:highlight" => "function() { log('highlight'); }",
                    "select2:removing" => "function() { log('removing'); }",
                    "select2:removed" => "function() { log('removed'); }",
                    "select2:loaded" => "function() { log('loaded'); }",
                    "select2:focus" => "function() { log('focus'); }",
                    "select2:blur" => "function() { log('blur'); }",
                ]               

                ], 

            'dataOperazione'=>['type'=> Form::INPUT_WIDGET, 
                'widgetClass'=>'kartik\datecontrol\DateControl',
                'options'=>[ 'pluginOptions'=>['autoclose' => true], ],
                'style'=>'width:190px',

                ], 
            ]
        ],  
    ]
    ]);

**Comment by kartik-v** [comment]
You obviously are passing the `pluginEvents` wrongly (note it is not a property of this extension).

You may want to read [the extension documentation](http://demos.krajee.com/builder) carefully and thoroughly once again. `FormGrid` is basically a grid of various `Form` widgets - so you should read the [Form builder docs](http://demos.krajee.com/builder-details/form).

The `pluginEvents` is a part of the individual Krajee widget settings and not a part of Form builder. So you must set it within the `options` property (corrected below):

```php
echo FormGrid::widget([
    'model' => $model,
    'form' => $form,
    'autoGenerateColumns'=>false,
    'rows'=>[   
        [
        'columns'=>2,
        'attributes' => [
            'tipoOperazione'=>['type'=> Form::INPUT_WIDGET, 'widgetClass'=>'\kartik\widgets\Select2',  
                'options' => [
                    'data' => $datac,
                    'pluginEvents' => [
                        "change" => "function() { log('change'); }",
                        "select2:open" => "function() { log('open'); }",
                        "select2:opening" => "function() { log('select2-opening'); }",
                        "select2:close" => "function() { log('close'); }",
                        "select2:highlight" => "function() { log('highlight'); }",
                        "select2:removing" => "function() { log('removing'); }",
                        "select2:removed" => "function() { log('removed'); }",
                        "select2:loaded" => "function() { log('loaded'); }",
                        "select2:focus" => "function() { log('focus'); }",
                        "select2:blur" => "function() { log('blur'); }",
                    ]
                ],
            ], 
        ]
        ],  
    ]
]);
```

**Comment by luluclytie** [comment]
###对对对 ###
