### ISSUE TITLE
Autoclose Enhacement

### ISSUE THREAD

**Issue by ber5ien** [kartik-v/yii2-widget-select2#105]
Hi,

I noticed that on data extension there is an option to autoclose it
'autoclose' => true

I have tried it with SELECT2 but it's not working and the page is not displaying any erros.

is this feature available? 

'editableOptions'=> function ($model) use ($customerFilter) {
            return [                
                'header'=>'Customer', 
                'size'=>'md',     
                'format' => 'link',
                'asPopover' => true,       
                'displayValueConfig' => $customerFilter,           
                'inputType' => Editable::INPUT_SELECT2,
                'options'=>[                    
                        'theme' => 'krajee',
                        'data' => $customerFilter,   
                        'id'=> 'userUpdate',                        
                        'pluginOptions'=>[
                               'allowClear' => true,
                              'autoclose' => true
                        ],
                ],                                    
            ];
        },        

Big Thanks!

**Comment by kartik-v** [comment]
No the source plugin does not have any such property `autoclose` available. You may need to write your own code using events of the select2 plugin to achieve your use case.

BTW there is a [new Q&A forum created for questions and programming tips](http://webtips.krajee.com/questions).
