### ISSUE TITLE
CSS declaration causes navbar to appear over modal windows

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-widget-select2#108]
###### Description

[This CSS declaration](https://github.com/kartik-v/yii2-widget-select2/blob/6f0b4c771404a42dc026e4480baf8fb583403ddd/assets/css/select2-krajee.css#L297) sets the *.navbar* z-index to **1055** while the [bootstrap modal windows z-index](https://github.com/twbs/bootstrap/blob/78bdbcdc0858efc57273da6f0d3f772076919e2f/less/variables.less#L278) is **1050**.
This of course makes any navbar panel appear over modal windows unless a workaround is applied (overriding the z-index or moving the modal window further down the Y axis).

###### Screenshot
![screenshot image](http://i.imgur.com/rfOBQ83.png)

###### Proposed solution
Why not adjust the z-index of *.select2-container* when it is contained somewhere inside *.navbar* (```.navbar .select2-container { z-index: ... }```) rather than directly modifying the z-index of *.navbar*?

**Comment by kartik-v** [comment]
This is beyond the scope of this widget. It entirely depends on how the developer is rendering markup. Note Select 2 in your case above does not lie inside the navbar. It lies rather inside the modal container. And the bootstrap modal container is always appended to the body element at the end. Check the output via browser console.

**Comment by vercotux** [comment]
> This is beyond the scope of this widget. 

Indeed. So why not remove the ```.navbar { z-index: 1055; }``` declaration and let the developer deal with it?

**Comment by kartik-v** [comment]
Yes.. that is a part of the default krajee theme (which can be changed). It was done for an earlier requirement and probably should be removed.

**Comment by kartik-v** [comment]
This is fixed now.

**Comment by vercotux** [comment]
Tested & lookin' good! Thank you.
