### ISSUE TITLE
Retrieving multiple 'id' => 'text' pairs in Select2

### ISSUE THREAD

**Issue by iadj** [kartik-v/yii2-widget-select2#111]
I have a Select2 field for multiple `'id' => 'text'` pairs using AJAX typeahead.

IDs are exploded into a comma separated string and then saved.

When I want to update a model, in the form view I try to retrieve the appropriate form field values like so:

    $users = [];
    if(!empty($model->users)){
      foreach($model::getUsers($model->id, false) as $user){
        array_push($additional_users, ['id'=>$user->id, 'username'=>$user->username]);
      }
      $users= \yii\helpers\ArrayHelper::map($additional_users, 'id', 'username');
    }
    $model->users= $users;

Printing the resulting array returns `[[24=>someusername],[44 => anotherusername]]`

The text values are displayed properly in the input field, but they no longer have the ID as `value` in the generated HTML. There's no value at all, just `title`, and saving it as such will try to save the attribute with the usernames as the value instead of the IDs. How do I properly return the `id => text` array into the Select2 field?

**Comment by iadj** [comment]
Here's what the form field looks like:

      <?= $form->field($model, 'users')->widget(Select2::classname(), [
          'options' => [
            'multiple' => true,
          ],
          'toggleAllSettings' => [
              'selectLabel' => false,
            ],
          'pluginOptions' => [
            'allowClear' => true,
                    'minimumInputLength' => 3,
                    'ajax' => [
                        'url' => Url::to(['/user/default/list-users']),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }'),

                    ],
                    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                    'templateResult' => new JsExpression('function(user) { return user.text; }'),
                    'templateSelection' => new JsExpression('function (user) { return user.text; }'),
                  ],
      ]) ?>

**Comment by kartik-v** [comment]
This is more a Yii Dropdown List question.

Your value field for multiple select input must just be a linear array of values (not an associative array).

For example if your list is `[[24=>someusername],[44 => anotherusername]]` and you have selected 24 and 44, then your value for update model should just be `[24, 44]`.

**Comment by iadj** [comment]
@kartik-v In that case, how do I assign a different text to the returned values?
When I select an item generated with Typeahead, I get what I want:
    <option value="44">username</option>
    <option value="45">username2</option>

This is saved as `44, 45`

On the model's `update` view, when I explode the array of IDs to put back into the Yii2 Select2 field, this is what the HTML becomes:
    <option value="44">44</option>
    <option value="45">45</option>

**Comment by kartik-v** [comment]
Your select2 `data` and `value` are different

```php
 // this is the value
$model->attribute = [44, 45];

// the data for list will include the text
echo Select2::widget([
    'model' => $model,
    'attribute' => 'attribute',
    'data' => [44 => 'text1', 45 => 'text2'], // this will ensure the text is displayed
]):
```

**Comment by iadj** [comment]
Perfect, that works. I originally thought the `'data'` option was for an array of data that the user could select from when using Select2's Dropdownlist and such. Thank you!

**Comment by npsoftwarepeternagy** [comment]
Hello kartik-v, 
I am facing the following problem:
I am using the yii2 framework and want to display a select box, which is:
 multiselect - done
displays the saved values on update - done
if I add a value - should send the keys of all the values- problem

It is sending the first already saved "descriptions" and the value of the new selected country..

Can you correct my script?

`$preSelectedCountries = \yii\helpers\ArrayHelper::map($seasonRule->getCountriesForRule($model->ID), 'id', 'text') ;

            $url = \yii\helpers\Url::to(['country-list']);
            //'initValueText' => $country, // set the initial display text

            echo $form->field($model, 'countryCode')->widget(Select2::className(), [
                'model' => $model,
                'attribute' => 'countryCode',

                'options' => [
                    'placeholder' => 'Search for a country ...',
                    'multiple' => true,
                    'value' => $preSelectedCountries,

                ],
                'pluginOptions' => [

                    'allowClear' => true,
                    'minimumInputLength' => 3,
                    'language' => [
                        'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
                    ],
                    'ajax' => [
                        'url' => $url,
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }')
                    ],
                    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                    'templateResult' => new JsExpression('function(country) { return country.text; }'),
                    'templateSelection' => new JsExpression('function (country) { return country.text; }'),
                ],
            ]);`

if I submit the form, it will send:


SeasonRule[countryCode][] | […]
-- | --
0 | Österreich
1 | Slowakei
2 | AL

where the 0 and 1 is the description of the saved values, the AL is the key of the selected (also same way displayed value)
please advice what to do, how can I define keys and descriptions, so I can see the name of the country, but after POST, it will send AT and SK instead of Österreich and Slowakei?

**Comment by npsoftwarepeternagy** [comment]
found the solution, if somebody needs it:
` echo $form->field($model, 'countryCode')->widget(Select2::className(), [
                'model' => $model,
                'attribute' => 'countryCode',
                'data' => $preSelectedCountries,
                'options' => [
                    'placeholder' => 'Search for a country ...',
                    'multiple' => true,
                    'value' => array_keys($preSelectedCountries),

                ],`
