### ISSUE TITLE
Setting data from AJAX response does not work

### ISSUE THREAD

**Issue by MacGyer** [kartik-v/yii2-widget-select2#112]
Hello,

I really like using your Yii2 extension Select2.
But I don't get one use case working:

After having requested some data by an AJAX call I can't set the response onto an existing Select2.

The response is JSON and has the following format:

```
response : {
   results: {
      0 : {
         id: ...,
         text: "..."
      },
      1 : {
         id: ...,
         text: "..."
      }
   }
}
```

I am setting the data like follows:

```
request.done(function (response) {
   $('#id-of-select2-element').select2('data', response);
});
```

But the options list is always empty. If I programmatically append options to the underlying select, it works.

Those are the options generated by the input widget:

```
var s2options_6cc131ae = {
   "themeCss": ".select2-container--bootstrap",
   "sizeCss":"",
   "doReset":true,
   "doToggle":false,
   "doOrder":false
};
var select2_03f54e93 = {
   "allowClear": true,
   "theme": "bootstrap",
   "width": "100%",
   "placeholder": "Type to search ...",
   "language": "en-US"
};
```

This is how the widget is called:

```
<?= $form->field($model, 'attribute')->widget(Select2::className(), [
         'options' => [
             'multiple' => true,
        ]) 
?>
```

What am I doing wrong?
Appreciate your help. Thx

**Comment by paskuale75** [comment]
Me too, same problem, scenario: ajax-content for Tabs-x widget with form content (select2 widget in it)

**Comment by dhimancontact** [comment]
use this http://demos.krajee.com/widget-details/depdrop
