### ISSUE TITLE
No work to save form

### ISSUE THREAD

**Issue by bogdandin** [kartik-v/yii2-widget-select2#113]
Hi, i replaced this 
   <?= $form->field($model, 'domeni_carte')->textInput() ?>

with

```php
 <?php
  
  // Multiple select without model
echo Select2::widget([
   'name' => 'domeni_carte',
   'value' => '',
   'data' => [ 0 => 'super', 2 => 'natural'],
   'options' => ['multiple' => true, 'placeholder' => 'Select states ...']
]);
  
  ?>
```

And now work to save form.... no errors

**Comment by iacobliviu** [comment]
Hi ,

You can use something like : 
$form->field($model, 'domeni_carte')->widget(Select2::classname(),
[
'name' => 'domeni_carte',
'value' => '',
'data' => [ 0 => 'super', 2 => 'natural'],
'options' => ['multiple' => true, 'placeholder' => 'Select states ...']
]
);
