### ISSUE TITLE
The plugins with my html templete static conflict

### ISSUE THREAD

**Issue by oneword** [kartik-v/yii2-widget-select2#116]
sorry my English is bad.
when I composer this plug-in, my html templete's static file conflict with this plug-in,for example jquery.js. The page include two jquery.js. Not just this plugin has this problem.

**Comment by kartik-v** [comment]
You may need to read yii2 documentation on handling and register ing assets and using yii asset manager to setup your assets.

**Comment by oneword** [comment]
Ok,thankyou very much ,I'll try it.

**Comment by oneword** [comment]
My English is terrible, so ,if I have some questions , I would like ask you,please help me, thank you.
