### ISSUE TITLE
initial value not working when Usage with ActiveForm and model

### ISSUE THREAD

**Issue by faravaghi** [kartik-v/yii2-widget-select2#120]
hi, when usage this widget with ActiveForm and mode initial value not working and do not show any tag.

```php
echo $form->field($model, 'tags')
->widget(Select2::classname(), [
	'value' => [0,1],
	'data' => $tags,
	'options' => [
		'placeholder' => Yii::t('object', 'Insert Tags...'),
		'multiple'=>true,
	],
	'pluginOptions' => [
		'tags' => true,
	]
]);
```
but when use below work fine!
```php
echo Select2::widget([
	'value' => [0,1],
	'data' => $tags,
	'options' => [
		'placeholder' => Yii::t('object', 'Insert Tags...'),
		'multiple'=>true,
	],
	'pluginOptions' => [
		'tags' => true,
	]
]);
```
please resolved it. tahnk you...

**Comment by kartik-v** [comment]
Please read yii 2 documentation for model attributes and input widgets before using any these widgets.

You do not assign a value that way when using with model. You directly set your model attribute value as a init value.

For example for your case

```php
$model->tags = [0,1];
echo $form->field($model, 'tags')
->widget(Select2::classname(), [
    //options
]);
```

**Comment by gitartur** [comment]
> Please read yii 2 documentation for understanding model attributes and input widgets before using any of these widgets.
> 
> You do not assign a value that way when using with model. You directly set your model attribute value as a init value.
> 
> For example for your case
> 
> ```
> $model->tags = [0,1];
> echo $form->field($model, 'tags')
> ->widget(Select2::classname(), [
>     //options
> ]);
> ```

+ 'data' => $tags,
