### ISSUE TITLE
Uncaught TypeError: Cannot read property 'opener' of null

### ISSUE THREAD

**Issue by sevshum** [kartik-v/yii2-widget-select2#122]
After last yii2 update of jQuery (from 2.1.4 to 2.2.0) something went wrong in js code and cause an error Uncaught TypeError: Cannot read property 'opener' of null.
Like workaround I apply 
'assetMap' => [
                'jquery.js' => '@web/js/jquery2.1.4.min.js',
            ],

**Comment by kartik-v** [comment]
Could be [related to this issue](https://github.com/jquery/jquery/issues/2866)

**Comment by kartik-v** [comment]
Could be [related to this issue](https://github.com/jquery/jquery/issues/2866). But it seems you may need to contact select2 plugin author for any fix on this.
