### ISSUE TITLE
Change 'pluginEvents' into documentation

### ISSUE THREAD

**Issue by samael** [kartik-v/yii2-widget-select2#123]
```php
pluginEvents = [
    "change" => "function() { log('change'); }",        // WORK
    "select2:opening" => "function() { log('select2:opening'); }", // DONT WORK, fixed to 'select2-opening'
    "select2:open" => "function() { log('open'); }", // DONT WORK, fixed to 'select2-open'
    "select2:closing" => "function() { log('close'); }", // DONT WORK, fixed to 'select2-closing'
    "select2:close" => "function() { log('close'); }", // DONT WORK, fixed to 'select2-close'
    "select2:selecting" => "function() { log('selecting'); }", // DONT WORK, fixed to 'select2-selecting'
    "select2:select" => "function() { log('select'); }", // DONT WORK, fixed to 'select2-select'
    "select2:unselecting" => "function() { log('unselecting'); }", // DONT WORK, fixed to 'select2-unselecting'
    "select2:unselect" => "function() { log('unselect'); }"  // DONT WORK, fixed to 'select2-unselect'
];
```

**Comment by kartik-v** [comment]
No your update is wrong... the docs show it correctly as per plugin docs.

Check [Select2 plugin events documentation](https://select2.github.io/examples.html#events).

**Comment by samael** [comment]
` $form->field($item, 'category_id', ['showLabels' => false])->widget(Select2::classname(), [
                                                'options' => [
                                                        'placeholder' => Yii::t('list', 'category')
                                                ],
                                                'pluginOptions' => [
                                                        'data' => new JsExpression(Json::encode($categories)),
                                                        'formatSelection' => new JsExpression('selection_w_parent'),
                                                        'allowClear' => false
                                                ],	
                                                'pluginEvents' => [
                                                        "select2-selecting" => "function(data) {
                                                        $(this).select2('close');
                                                        if (data.val == 'none') {
                                                                $.get('/shopping/add-category', {id: $('#list-id').val()}, function (data) {
                                                                        $('#category-add .modal-body').html(data);
                                                                        $('#category-add').modal();
                                                                });
                                                                return false;
                                                        }
                                                }",
                                                ],
                                        ])`
It's part of working code. How you can see I'm using "select2-selecting" cause "select2:selecting" not fired. When I changed that ":" to "-" all events work fine but with ":" events not work. Using yii 2.0.7, jquery 2. May be I'm wrong. But that true.
