### ISSUE TITLE
Uncaught ReferenceError: select2_d648201d is not defined

### ISSUE THREAD

**Issue by harshitchaudhary** [kartik-v/yii2-widget-select2#129]
I am facing some JS issues not sure why they are. I am attaching a screenshot of console 

![screenshot from 2016-03-05 17 15 09](https://cloud.githubusercontent.com/assets/4983996/13547367/1e0110ba-e2f6-11e5-8e29-da3bc1695725.png)

Thanks in advance

**Comment by kartik-v** [comment]
You need to debug your code (basically JS dependencies and how you are loading your core assets and other plugins).

If you are loading content by AJAX you need to ensure you have the dependent content loaded in HEAD and use appropriate methods like renderAjax to render content if needed.

**Comment by AlikKosarevskiy** [comment]
Hi harshitchaudhary! Do you find the solution for your trouble?
I have the same Uncaught ReferenceError: select2_11dcd82c is not defined, and start to investigate.

**Comment by harshitchaudhary** [comment]
Yeah, actually I followed whatever @kartik-v have mentioned and thereafter it worked. Just make sure your register your jquery and select2.js before registering your class or id with select2

Here is my working sequence. I hope you might get some idea with that.
![screenshot from 2016-05-21 14-17-41](https://cloud.githubusercontent.com/assets/4983996/15447512/74309cdc-1f62-11e6-838f-2a81aa0b55c4.png)

**Comment by AlikKosarevskiy** [comment]
Thank you guys, it works now!

**Comment by onovikov09** [comment]
Hello!
I had a problem in that I in a template deleted a call $this->head().

**Comment by maskeyarun** [comment]
I'm using with AJAX and getting same problem. Please suggest where should I inject the dependencies. There is a clone button and once the RenderAjax get's cloned it will append result into a table. 
first page:
                    <td><?= $form->field($modelMeta, 'rate')->textInput(['maxlength' => true])->label(FALSE) ?></td>
                    <td><?= $form->field($modelMeta, 'qty')->textInput()->label(FALSE) ?></td>
                    <td><?= $form->field($modelMeta, 'amount')->textInput(['maxlength' => true])->label(FALSE) ?></td>
                    <td>
                        <span class="btn btn-primary glyphicon glyphicon-plus-sign " onclick="pometaclone()"></span>
                        <span class="btn btn-danger glyphicon glyphicon-minus-sign hide minus" onclick="$(this).closest('tr').remove();"></span>
                    </td>
                </tr>
            </tbody>
        </table>
        <?= $form->field($model, 'purchaseterm')->textarea(['rows' => 6]) ?>

        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>
<div class="row makespace"></div>
<?php
$this->registerJs($this->render('po.js'), \yii\web\View::POS_HEAD);

=========== Controller
public function actionPorawclone($purcount) {
        $meta = new \app\models\PurchaseOrdermeta();
        $rawList = ArrayHelper::map(\app\models\MasterRawitems::find()->all(), 'id', 'raw_name');
        $unitList = ArrayHelper::map(\app\models\InventoryUnits::find()->all(), 'id', 'unitcode');
        return $this->renderAjax('porawclone', [
                    'meta' => $meta,
                    'rawList' => $rawList,
                    'unitList' => $unitList,
                    'key' => $purcount
        ]);
    }
======================Ajax rendered
<?php

use kartik\select2\Select2;
use yii\bootstrap\ActiveForm;
?>
<?php
$form = ActiveForm::begin();
?>
<tr>
    <td>
        <?php
        echo $form->field($meta, 'particular[]')->widget(Select2::classname(), [
            'data' => $rawList,
            'language' => 'en',
            'options' => ['placeholder' => 'Select Raw material ...', 'class' => 'sitem', 'id' => 'rawid' . $key],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ])->label(FALSE);
        ?>
    </td>
    <td>
        <?php
        echo $form->field($meta, 'unit[]')->widget(Select2::classname(), [
            'data' => $unitList,
            'language' => 'en',
            'options' => ['placeholder' => 'Select Unit ...', 'class' => 'sitem', 'id' => 'unitid' . $key],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ])->label(FALSE);
        ?>
    </td>
    <td>
        <?= $form->field($meta, 'rate[]')->textInput(['maxlength' => true])->label(FALSE) ?>
    </td>
    <td>
        <?= $form->field($meta, 'qty[]')->textInput()->label(FALSE) ?>
    </td>
    <td>
        <?= $form->field($meta, 'amount[]')->textInput(['maxlength' => true])->label(FALSE) ?>
    </td>
    <td>
        <span class="btn btn-primary glyphicon glyphicon-plus-sign " onclick="pometaclone()"></span>
        <span class="btn btn-danger glyphicon glyphicon-minus-sign minus" onclick="$(this).closest('tr').remove();"></span>
    </td>
</tr>

**Comment by fredyns** [comment]
does anyone trying this lately?
seems there is some script try to mention undefined variable.

in some line mentioned as (in my case):
```
window.select2_21c9e67b = {"allowClear":true,"tags":false,"minimumInputLength":2,"lang...};
```

but later script mentioned as:
```
jQuery.when(jQuery('#book-author_id').select2(select2_21c9e67b)).done(initS2Loading('book-author_id','s2options_d6851687'));
```

can anyone help?

**Comment by maskeyarun** [comment]
I got same problem a year a go, after I declared that in script it worked
fine.

Did it come while there are multie select2

**Comment by iamnareshsaini** [comment]
It occurred to me as I did not close my form . 
```
 $form = ActiveForm::begin([
            'enableAjaxValidation' => false,
        ]);
 echo Select2::widget([
                    'id' => $selector,
                    'name' => 'Name',
                    'data' =>[],
                    'options' => [
                        'multiple' => false,
                        'placeholder' => Yii::t('app', 'Select')
                    ]
                ]);
``` 
should be end with 
```
TActiveForm::end()
```
