### ISSUE TITLE
Add ability to hide search control and use as normal select

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-widget-select2#13]

**Comment by kartik-v** [comment]
New property `hideSearch` added to Select2 widget. Check fourth example on usage section of [the demos page](http://demos.krajee.com/widget-details/select2).

**Comment by stakanov** [comment]
Hello Kartik,
I updated widget package, but there is an error:
```
Setting unknown property: kartik\select2\Select2::hideSearch
```

**Comment by kartik-v** [comment]
Your package is not updated - cross check with the source from `dev-master` - I have not tagged a new release yet.
