### ISSUE TITLE
How to require field without model?

### ISSUE THREAD

**Issue by tuannda** [kartik-v/yii2-widget-select2#130]
```
<?= Select2::widget([
		'name' => 'category_id',
		'data' => $treeParents,
		'value' => $currentCategories,
		'options' => ['placeholder' => 'Category', 'multiple' => true],
		'pluginOptions' => [
			'tags' => true,
			'allowClear' => true,
			'maximumInputLength' => null,
		]
	]); ?>
```

category_id not define in database. How to validation it :)

**Comment by kartik-v** [comment]
Not related to this extension. This is programming to be done by each developer (using validation at controller level OR writing your own javascript). You may need to read Yii Documentation.

You can request for such programming help in the [Q & A webtips forum as well](http://webtips.krajee.com/questions).
