### ISSUE TITLE
Select 2 widget with limit on multiple selection 

### ISSUE THREAD

**Issue by macrawat** [kartik-v/yii2-widget-select2#132]
Hi kartik !!

I am using Select 2 widget with  options as "multiple => true". How can i set limit on mutiple selections as suppose there are 25 dropdown items and i want user to choose 5 from them.
I tried  "maximumSelectionLength: 5" with the options but it is not working.
Can you suggest any measure to do that ?
Thanks

**Comment by macrawat** [comment]
Okay this works for me by setting
'showToggleAll' => false,
and in 'pluginOptions' => [
                            'maximumSelectionLength'=> 3,
                        ],

**Comment by chandani123** [comment]
Hi kartik !!

I am using Select 2 widget with options as "multiple => true". How can i set limit minimum selection length  in multi select Drop downlist. can you help me ?
Thanks

**Comment by mohammad1381** [comment]
Hi, you can use this code in **pluginOptions**

```
 'pluginOptions' => [
        'minimumInputLength' => 10
 ],
```

**Comment by abelwamana** [comment]
Hi. 
I am using Tagging Support mult-select for your widget SELECT2 as  "multiple => true", but when i have a lote of itens/text it can not be select all.
see my codifcation:
<?=
$form->field($eventModel, 'participantes')->widget(Select2::classname(), [
'data' => ArrayHelper::map(Contacto::find()->all(), 'email', function ($model) {
return $model->nome . ' - ' . $model->instituicao;
}),
'options' => ['placeholder' => 'Selecione os participantes...', 'multiple' => true, 'id' => 'select-participantes'],
'pluginOptions' => [
'allowClear' => true,
],
]);
?>
![Captura de ecrã 2024-07-24 170629](https://github.com/user-attachments/assets/3f2c97e0-d0ad-442e-b774-a0890c83a595)
