### ISSUE TITLE
Avast is marking as virus

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/yii2-widget-select2#136]
Hey there, my avast is marking this file https://github.com/kartik-v/yii2-widget-select2/blob/master/assets/js/i18n/lt.js as a virus. Any ideas why ? + I can't understand that code some part of it..

**Comment by kevin-brown** [comment]
This appears to be an Avast! issue, there's a duplicate posted upstream about `pt-BR.js`: https://github.com/select2/select2/issues/4263
