### ISSUE TITLE
Select2.php returns error on empty values

### ISSUE THREAD

**Issue by iadj** [kartik-v/yii2-widget-select2#138]
Not sure if this is intended by the module, but when my Select2 field is empty, it's handled as an empty `''` string in Select2.php making it 'set' and causing an error in Select2 because it's trying to 'combine' a string instead of an array.

I fixed this by changing lines 185 and 186 in Select2.php:

```
    if (!isset($this->data)) {
            if (!isset($this->value) && !isset($this->initValueText)) { 
```

to:

```
    if (empty($this->data)) {
            if (empty($this->value) && empty($this->initValueText)) { 
```

**Comment by kartik-v** [comment]
No this is incorrect.

- `empty` will return true if value is also a `0` - thus making it incorrect if user needs a value `0` in the dropdown.
- also you should not be invalidating empty strings... since it can be a valid value in dropdowns... the only way is to check if it is null..

**Comment by iadj** [comment]
I forgot to mention, this issue only seems to appear with the option `multiple` enabled. I believe what happens is that when nothing is selected, an empty string is passed and it is expected by Select2 to be an array.

**Comment by iadj** [comment]
I guess a better possible solution would be to check if the variable is an array, and if not to pass it to a new array before handling the rest?
