### ISSUE TITLE
When using multiple = true and ActiveField and AJAX, the value is not shown

### ISSUE THREAD

**Issue by Oreolek** [kartik-v/yii2-widget-select2#139]
`Select2::widget()` works fine but when using `$form->field($model, $attribute)->widget(Select2::classname())` the model value is not shown, select2 comes up as empty.

**Comment by kartik-v** [comment]
Cannot reproduce what you are mentioning.

Do you have an example and the config you are using?

**Comment by Oreolek** [comment]
Hmm, it might be a documentation problem. As I understand it should be like:
```
echo $form->field($model, $attribute)->widget(Select2::classname(), [
        'initValueText' => $model->attribute_text,
]);
```
so the values ($model->attribute, an array of IDs) are combined with text and displayed. Is that right? There's no example for multiple selects w/AJAX.

**Comment by kartik-v** [comment]
`initValueText` is the description of the selected option.... while the attribute value will be the id of the selected option.
