### ISSUE TITLE
In modal window loaded with "renderAjax" search box seems disabled.

### ISSUE THREAD

**Issue by aaron-cardenas** [kartik-v/yii2-widget-select2#142]
I have the widget in a modal window loaded with "renderAjax". Any ideas why the widget does not have the search box active? The search box is visible, but I cannot use it to search (seems disabled)

**Comment by tobnjoy** [comment]
Hi,
Please add the following code to the current page
<?php
$format = <<< SCRIPT
$.fn.modal.Constructor.prototype.enforceFocus = function() {};
SCRIPT;
$this->registerJs($format, \yii\web\View::POS_READY);
?>

**Comment by kartik-v** [comment]
Refer [select 2 widget demos and scroll to the example for Bootstrap modal dialog](http://demos.krajee.com/widget-details/select2). You may need to [set tabindex property to false as reiterated here](https://github.com/kartik-v/yii2-widgets/issues/302#issuecomment-212781020).
