### ISSUE TITLE
how could i make them dependent like multi state with multi city please guide me ?

### ISSUE THREAD

**Issue by ashutosh1812** [kartik-v/yii2-widget-select2#143]

**Comment by kartik-v** [comment]
Please review [the guidelines for contributing](https://github.com/kartik-v/yii2-widget-select2/blob/master/.github/CONTRIBUTING.md) to this repository.

Please use this repo for only reporting plugin issues - you can request for programming help in the [webtips forum](http://webtips,krajee.com).
