### ISSUE TITLE
How to Add Jquery for Option Group?

### ISSUE THREAD

**Issue by InsaneSkull** [kartik-v/yii2-widget-select2#144]
I want to allow only one selection per option group. how to do it?

How to convert below script to work on  select2?

    $('select optgroup option').click(function () {
      var len = $(this).parent().find(':selected').length
       if (len > 1) {
            $(this).prop('selected', false);
       }
    });

**Comment by kartik-v** [comment]
You need to write your own jquery for this... you could search the programming help online or use [Krajee Webtips Forum](http://webtips.krajee.com) to get programming tips.
