### ISSUE TITLE
Last item can't be removed in multiple GridView filter

### ISSUE THREAD

**Issue by shum16** [kartik-v/yii2-widget-select2#145]
I'm using Select2 as a multiple GridView filter. And it works fine afterall, except for one thing: it's not possible to remove the last selected item from the list. Every time I try to do that, it reloads the grid with the same item in the filter, - becasue the value comes again with $_GET array!

Here's how it looks like:
![filter](https://cloud.githubusercontent.com/assets/10737487/14739788/9adf1dcc-0892-11e6-9235-191cd3918d83.png)

Here's the column definition:

```
[
            'label' => 'Status',
            'class' => 'kartik\grid\DataColumn',            
            'attribute' => 'kid_status',            
            'filter' => Select2::widget([
                'name' => 'kid_status',             
                'data' => ['1' => 'status 1', '2' => 'status 2', ],
                'value' => isset($params['kid_status']) ? $params['kid_status'] : null,
                'language' => 'ru',
                'options' => [             
                    'placeholder' => 'Select status...',
                    'multiple' => true
                ],
                'pluginOptions' => [
                    'tags' => true,                     
                    'allowClear' => false,
                ],                    

             ]),                    
            'vAlign'=>'middle',
            'hAlign'=>'center',             
            'width' => '130px !important '
        ],      
```

**Comment by shum16** [comment]
I wonder if nobody uses Select2 as a multifilter...

**Comment by armpogart** [comment]
@shum16 I have the same issue, after clearing the last item, it remains there.

**Comment by shum16** [comment]
up!

**Comment by abalest14** [comment]
i have the same issue, please help us!

**Comment by abalest14** [comment]
no fix or workaround for this issue? thanks

**Comment by kartik-v** [comment]
Will need to check on this...

**Comment by kartik-v** [comment]
Set `allowClear` to `true` and then use the CLEAR cross button to clear the multi select.

**Comment by shum16** [comment]
Kartik, this solution doesn't work!

**Comment by abalest14** [comment]
Even for me dosent work. At the moment i have resolved moving the search
fields outside the gridview like this work like a sharm.

Il 15/ago/2016 14:19, "shum16" <notifications@github.com> ha scritto:

**Comment by shum16** [comment]
Kartik, any news on this issue?

**Comment by kartik-v** [comment]
Will need to study this. Unfortunately it seems this is out of scope of both the Select2 widget as well as this extension... but more to do with how you load search model using mass assignment and write your search method to filter grid rows. There needs to be some way you can trap the last unselected data.

Will check back to see if there is something that can be done here when I get some time.

**Comment by shum16** [comment]
@kartik-v , ok, thank you.

**Comment by shum16** [comment]
@kartik-v  any news on this issue?

**Comment by kzpromo** [comment]
i have the same problem, @kartik-v can you help?

**Comment by abalest14** [comment]
this issue still not resolved? i have start a new project and still have the problem. thanks

**Comment by pamkil** [comment]
Whether is understanding when it is possible to wait for a fix of this problem? thanks.

**Comment by DarkDrim** [comment]
I have this issue also..
Somebody know how to fix this?

**Comment by kartik-v** [comment]
Not sure this is an issue any more. It depends on how you are configuring this.

Check the [updated grid demo](http://demos.krajee.com/grid-demo) - the author is a multi select filter and seems to work like a charm. Go through the demo config and let know if any issues.

**Comment by playwolf719** [comment]
@kartik-v hi, same issue, what's the solution? Anyone can help me

**Comment by cornernote** [comment]
I got it to work by adding a hidden input with the same name right before the select2, eg:

```
$columns[] = [
    'attribute' => 'status',
    'filter' => Html::hiddenInput('CompanySearch[status]')
        . Select2::widget([
            'name' => 'CompanySearch[status]',
            'value' => $searchModel->status,
            'data' => $data,
            'options' => [
                'multiple' => true,
            ],
        ]),
]
```

**Comment by kartik-v** [comment]
As mentioned before - check the [updated grid demo](http://demos.krajee.com/grid-demo) - the author is a multi select filter and seems to work like a charm. Go through the demo config and let know if any issues.

**Comment by Daniel123wq** [comment]
> I got it to work by adding a hidden input with the same name right before the select2, eg:
> 
> ```
> $columns[] = [
>     'attribute' => 'status',
>     'filter' => Html::hiddenInput('CompanySearch[status]')
>         . Select2::widget([
>             'name' => 'CompanySearch[status]',
>             'value' => $searchModel->status,
>             'data' => $data,
>             'options' => [
>                 'multiple' => true,
>             ],
>         ]),
> ]
> ```
this working, tky.
