### ISSUE TITLE
issue with select2 multiple in dynagrid

### ISSUE THREAD

**Issue by sebako86** [kartik-v/yii2-widget-select2#146]
Hi Kartik,

got an issue with the select2 when using it as a filter in dynagrid. As long as I use multiple=>false it works fine, when I set it to true I get an Exception from BaseHtml of the yii framework about array to string conversion.

The error is coming from BaseHtml line 513 in this line: 
`$options['value'] = $value === null ? null : (string) $value;`

seems like yii is trying to cast the value to string in order to place it within the input field, not sure why tho. 

Grid Column:
`[
        'attribute'=>'geos',

        'vAlign'=>'middle',

        'width'=>'210px',
        'value'=>function ($model, $key, $index, $widget) { 
            return $model->getOfferCountries();
        },`

        'filterType'=>GridView::FILTER_SELECT2,
        'filterWidgetOptions'=>[
            'pluginOptions'=>[
                'minimumInputLength' => 2,
                'allowClear'=>false,
                'tags'=>true,
                'multiple'=>true,
                'tokenSeparators' => [',', ' '],
                'templateResult' => new JsExpression('format'),
                'templateSelection' => new JsExpression('format'),
                'ajax' => [
                    'url' => Url::to(['offers/geos']),
                    'dataType' => 'json',
                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                ],
            ],
        ],

        'filterInputOptions' => ['placeholder' => 'Geo'],

        'format'=>'raw'

    ],`

**Comment by shum16** [comment]
I think this is common issue..
As a workaround you could use my solution - I solved this by using a pure filter without a model. Here's my configuration:
```
[
            'label' => 'Status',
            'class' => 'kartik\grid\DataColumn',            
            'attribute' => 'kid_status',            
            'filter' => Select2::widget([
                'name' => 'kid_status',             
                'data' => ['1' => 'status 1', '2' => 'status 2', ],
                'value' => isset($params['kid_status']) ? $params['kid_status'] : null,
                'language' => 'ru',
                'options' => [             
                    'placeholder' => 'Select status...',
                    'multiple' => true
                ],
                'pluginOptions' => [
                    'tags' => true,                     
                    'allowClear' => false,
                ],                    

             ]),                    
            'vAlign'=>'middle',
            'hAlign'=>'center',             
            'width' => '130px !important '
        ],
```

**Comment by sebako86** [comment]
@shum16 thanks, so far this seem to work, however now if I select from my results I get the spinner but tags are not applied.

My Updated Code:

`'attribute'=>'geos',
            'vAlign'=>'middle',
            'width'=>'210px',
            'value'=>function ($model, $key, $index, $widget) { 
                return $model->getOfferCountries();
            },
            'filter' => Select2::widget([
                'name' => 'geos',
                'value' => empty(Yii::$app->request->getQueryParams()['geos']) ? null : Yii::$app->request->getQueryParams()['geos'],
                'language' => 'en',
                'options' => [             
                    'placeholder' => 'Countries',
                    'multiple' => true,
                ],
                'pluginOptions' => [
                    'tags' => true,                     
                    'allowClear' => true,
                    'templateResult' => new JsExpression('format'),
                    'templateSelection' => new JsExpression('format'),
                    'language' => [
                        'errorLoading' => new JsExpression("function () { return 'Loading ...'; }"),
                    ],
                    'ajax' => [
                        'url' => Url::to(['offers/geos']),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }')
                    ],
                ],
             ]),
            'format'=>'raw'`

I am getting this error in the console: Uncaught TypeError: data.slice is not a function coming from hideplaceholder function in select2. Not sure if this is related but looks like it.

**Comment by shum16** [comment]
it seems like you got 2 'value' keys in your column configuration.

**Comment by shum16** [comment]
I think you should look at the search model to find out what is wrong. Do you properly filter 'geos' value there?

**Comment by sebako86** [comment]
got that working now, the issue was that on update of the select2 the pjax container reloaded, so I took search for those select2 out of the grid header into "advanced search"
