### ISSUE TITLE
kvInitPlugin is not defined

### ISSUE THREAD

**Issue by TJRoger** [kartik-v/yii2-widget-select2#148]
(index):325 Uncaught ReferenceError: kvInitPlugin is not defined(anonymous function) @ (index):325j @ jquery.js:3099k.fireWith @ jquery.js:3211n.extend.ready @ jquery.js:3417I @ jquery.js:3433
dump(e)
yii 2.0.8,

**Comment by mohammadkhairi** [comment]
i also have this problem. Does anyone have any solutions?

**Comment by kartik-v** [comment]
You need to have the latest release of the extension including dependencies i.e. `yii2-krajee-base`.

**Comment by TJRoger** [comment]
@mohammadkhairi It has something to do with the cache, you may using the old js/css resource files while using the latest release of the code.
