### ISSUE TITLE
Select2 events in dynamicform doesn't work correctly

### ISSUE THREAD

**Issue by yafater** [kartik-v/yii2-widget-select2#152]
I'm using select2 in [dynamic form](https://github.com/wbraganca/yii2-dynamicform)
,when I use events for select, the events works only for first nested form and It doesn't work for nested form that added by (+).How can I fix that?

**Comment by noorahmed94** [comment]
Same issue. Plus for the second row, Select 2 gives me this error:

```
ReferenceError: initSelect2Loading is not 
$.when($('#' + id).select2(configSelect2)).done(initSelect2Loading(id));
```

Need help with it

**Comment by kartik-v** [comment]
Sorry cannot help with this - as I am not aware of the 3rd party extension... you may need to contact the author for the same.
