### ISSUE TITLE
What are the best practices to avoid mixing the JavaScript and HTML in the views?

### ISSUE THREAD

**Issue by thecortex** [kartik-v/yii2-widget-select2#154]
Hello,

What are the best practices to avoid mixing the JavaScript and HTML in the views? If we define events callbacks for almost any of kartik widgets in the views. The views become messed up with JavaScript and HTML.

How can we achieve this separation?

Thank you in advance~

**Comment by kartik-v** [comment]
Suggest this be put up in the [webtips Q & A forum](http://webtips.krajee.com/questions). Closing this as not related to this extension.
