### ISSUE TITLE
Custom tag input in select2 ?

### ISSUE THREAD

**Issue by yatinmistry** [kartik-v/yii2-widget-select2#156]
Hello Kartik,

How to do custom tag input ?
Whatever use type it will tag .
Thanks,
Yatin Mistry

**Comment by kartik-v** [comment]
You may read [docs and demo examples](http://demos.krajee.com/widget-details/select2) for understanding. For any programming help, please do not use this forum... you can use the [webtips Q & A forum](http://webtips.krajee.com/questions) to post for help and tips
