### ISSUE TITLE
CSS fix shadows in Select2::THEME_BOOTSTRAP

### ISSUE THREAD

**Issue by twg-group** [kartik-v/yii2-widget-select2#158]
Hi Kartik, please fix if possible...

![issue_00](https://cloud.githubusercontent.com/assets/4106853/16224704/dc46210a-37ab-11e6-9e5f-9cd5d134dc92.jpg)

**Comment by kartik-v** [comment]
It uses the default plugin provided bootstrap theme.

You can submit a PR...  if you need to.
