### ISSUE TITLE
Can't type any thing in select2 with modal and gridView

### ISSUE THREAD

**Issue by destyl12** [kartik-v/yii2-widget-select2#159]
Hi,
I have modal with fields in select2 ( for filtering ), and below gridView for data. When I open my modal, a can't type any thing for search. BUT, when i select something from my dropdown list, input start working fine. 

It's must be something wrong with select2 and gridView, because when i removed gridView from modal, select work fine.

**Comment by kickhelp** [comment]
any news?

**Comment by kartik-v** [comment]
You need to check your code and javascript of how you are rendering in a modal - the jquery plugins can get broken if you are overwriting html without care...

Also check this separate [related comment of how to use select2 inside a bootstrap modal](https://github.com/kartik-v/yii2-widget-select2/issues/41#issuecomment-108466959)

**Comment by destyl12** [comment]
I fix that by adding in my js, line:
` $.fn.modal.Constructor.prototype.enforceFocus = $.noop; `

**Comment by kickhelp** [comment]
It work fine in all browsers, but not in firefox
