### ISSUE TITLE
Update Scenario for Select2 Multiple Ajax

### ISSUE THREAD

**Issue by gunturbudi** [kartik-v/yii2-widget-select2#160]
Hello kartik, i am using your select2 multiple in ajax. It's working fine in Create Scenario. But in Update Scenario, how do I set the initial value? Should it be with [id , text] pair? or just text? Because in my mind, text won't be working because the id was got from ajax.

Thank you

**Comment by gunturbudi** [comment]
i have set initValueText, and value as an array. But its not showing.

Here is my code:

`
echo Select2::widget([
                            'name' => 'diangosis_banding',
                            'options' => ['placeholder' => 'Pilih Diagnosis Banding', 'multiple' => true],
                            'pluginOptions' => [
                                'tags' => true,
                                'initValueText' => isset($rm_diagnosis_banding_text) ? $rm_diagnosis_banding_text : [],
                                'value' => isset($rm_diagnosis_banding_id) ? $rm_diagnosis_banding_id : [],
                                'allowClear' => true,
                                'minimumInputLength' => 3,
                                'language' => [
                                    'errorLoading' => new JsExpression("function () { return 'Mencari...'; }"),
                                ],
                                'ajax' => [
                                    'url' => Url::to(['diagnosis/cari']),
                                    'dataType' => 'json',
                                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                                ],
                                'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                                'templateResult' => new JsExpression('function(dat) { return dat.text; }'),
                                'templateSelection' => new JsExpression('function (dat) { return dat.text; }'),
                            ],
                        ]);
`

**Comment by gunturbudi** [comment]
Alright, my bad, i placed initValueText an value inside the pluginOptions.
When i placed outside, it works perfecly.
Thanks for the awesome plugin kartik!

**Comment by neovash23** [comment]
hi, can you give the array format you are passing inside the `initValueText`, i tried `[['id'=>333351,'text'=>'test']]`
