### ISSUE TITLE
Empty value in `multiple` mode

### ISSUE THREAD

**Issue by Kolyunya** [kartik-v/yii2-widget-select2#164]
Suppose we have `select2` widget in `multiple` mode attached to `foo` attribute of some model. No items are selected in that widget and an input has a value of empty string. 

Then we submit the form and it doesn't pass validation due to some validation rules. Model's `foo` attribute now has a value of an empty string (not `NULL`) and the form is being re-rendered (since it didn't pass validation).

Then bad things happen in `kartik\select2\Select2` at line `189`
~~~php
$key = isset($this->value) ? $this->value : ($multiple ? [] : '');
$val = isset($this->initValueText) ? $this->initValueText : $key;
$this->data = $multiple ? array_combine($key, $val) : [$key => $val];
~~~

1. ` isset($this->value)` evaluates to `true` since `$this->value` is an empty string.
2. `$key` gets a value of an empty string.
3. `array_combine()` recieves an empty string as a first argument.
4. `yii\base\ErrorException` is being thrown.

I'm not completely sure but as far as I can see changing `isset` to `!empty` at line `189` should fix the problem. I would be glad to make the PR if you confirm the issue and the solution.
Thank you!

**Comment by kartik-v** [comment]
I think just doing a plain `empty` check will be a wrong one - because it will eliminate values like `0`, an empty string `''`, or `false` as well. However, these can be valid values in a select dropdown.

It needs to be done a bit differently for `multiple` select only.

**Comment by Kolyunya** [comment]
@kartik-v can you confirm the issue or am I doing something wrong?

**Comment by Kolyunya** [comment]
~~~php
if ($multiple) {
    $key = is_array($this->value) ? $this->value : [];
} else {
    $key = isset($this->value) ? $this->value : '';
}
~~~

@kartik-v will something like this be sufficient?

**Comment by kartik-v** [comment]
Yes I think that should be something like it... will simplify this and create an enhancement.

**Comment by kartik-v** [comment]
Resolved via 2e77352.

**Comment by Kolyunya** [comment]
@kartik-v thank you for a quick patch and new release!

**Comment by JonasW91** [comment]
To obtain the key from `$key` on line `195`, it should look like this:
`$this->data = $multiple ? array_combine( array_keys( $key ) , $val) : [$key => $val];` 

If `$this->value` is e.g. something like this: 
`[32 => "Example"]` 
it becomes something like that:
`["Example" => "Example"]`
but actual it should look like this, should't it?
`[32 => "Example"]`
