### ISSUE TITLE
order

### ISSUE THREAD

**Issue by ph1ex0n** [kartik-v/yii2-widget-select2#17]
it's my code

```
<?= $form->field($model, 'filters')->widget(Select2::classname(), [
	    'data' => array_merge(["" => ""],['Filter 1'=>'Filter 1','Filter 2'=>'Filter 2','Filter 3'=>'Filter 3']),
	    'options' => ['multiple' => true,'placeholder' => 'Select a filter ...'],
	    'pluginOptions' => [
	        'allowClear' => true
	    ],
	]);
	?>    

```
what i do

![filters](http://i072.radikal.ru/1502/40/51417ad78046.png)

then i get

![filters1](http://s018.radikal.ru/i513/1502/b5/427df2589cdf.png)

how i can save the order of filters?

![filters2](http://s016.radikal.ru/i335/1502/04/4a1d3a8ffae5.png)

**Comment by kartik-v** [comment]
You would need to build the data structure for your use case. Treat it like a normal HTML select with multiple option. What you have for each selected item in the list are the following -> ID and VALUE. 
You can design in such a way that you can sort by ID and the VALUE is displayed.

**Comment by ph1ex0n** [comment]
i don't understood
please help

**Comment by kartik-v** [comment]
Your data for select must be an array of keys and values.
```php
'data'=>[
    1 => 'Filter 1',
    2 => 'Filter 2',
    3 => 'Filter 3',
    4 => 'Filter 4',
    5 => 'Filter 5',
];
```

When you have selected filters it can be saved in any order  `2, 1, 3 ` etc.

But when you return it back as a value you would return it sorted by the ID  (array key) - so your filters are sorted...
```
'value'=>[
    1 => 'Filter 1',
    2 => 'Filter 2',
    3 => 'Filter 3',
];
```

**Comment by ph1ex0n** [comment]
could you please provide such a possibility to your wrapper like https://github.com/tristanjahier/chosen-order?

**Comment by ph1ex0n** [comment]
please help

**Comment by kartik-v** [comment]
Not sure I will have time for enhancement on this.

But you can reorder the list easily from PHP server code before saving - is there any reason you want to do this by javascript?

As an alternative, you can look at the [Sortable Input](http://demos.krajee.com/sortable-input) extension which allows drag drop sort (using two connected sortables).

**Comment by ph1ex0n** [comment]
Thank you!

**Comment by xtarantulz** [comment]
2amigos/yii2-selectize-widget
this plugin like it, but he can sort.
