### ISSUE TITLE
Select2 gets green border, but keeps has-error class. Bug?

### ISSUE THREAD

**Issue by jeroenk22** [kartik-v/yii2-widget-select2#170]
Hi Kartik,

I'm using your `DetailView` widget inside a modal and i'm trying to send the form using ajax.
Now there's a problem. When I clear a `Select2` field (multiple) and try to submit the form there's a validation error. So far this is expected behaviour. But when I then select some values it should pass the validation, but unfortunately, it doesn't. The field gets a green border but still keeps the `has-error` class somehow. The class disappears when the field gets focus again.
This only happens with the `Select2` widget as far as I can see.

**My controller:**

```
    public function actionView($id) 
    {
        $planning = $this->findModel($id);
        $post = Yii::$app->request->post();
        
        if (Yii::$app->request->isAjax && $planning->load($post) && $planning->save()) {
                Yii::$app->session->setFlash('success', [
                    'type' => 'success',
                    'duration' => 10000,
                    'icon' => 'fa fa-check',
                    'message' => 'Opdracht is succesvol bijgewerkt.'.Html::button(Icon::show('hand-o-right', ['class' => ''], Icon::FA). Yii::t('app', 'View'), ['class' => 'btn btn-sm btn-success modalButton pull-right', 'data-notify' => 'dismiss', 'data-content' => Url::to(['planning/view', 'id' => $id])]),
                    'title' =>  Html::tag('span', 'Opdracht bijgewerkt', ['style' => 'font-weight: bold;']),
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
        }
        else {
            return $this->renderAjax('view', ['planning' => $planning]); 
        }
    }
```

**My JQuery:**

```
$('body').on('beforeSubmit', 'form#view_form', function () {
    
    var form = $(this);
    // return false if form still have some validation errors
    if (form.find('.has-error').length) {
        return false;
    }
    
    // submit form
    $.ajax({
        url: form.attr('action'),
        data: form.serialize(),
        type: 'post',
    }).done(function(){
        $('.modal').modal('hide');
        $.pjax.reload({
            container: '#planner_grid', 
            timeout: 10000, 
            replace: false
        });
    }).fail(function(){
        console.log('Server error...');
    }); 
    
    return false;
});
```

**Screenshot:**

![example](https://cloud.githubusercontent.com/assets/3177682/17935687/8c1a0a5e-6a1c-11e6-9bd3-549944800008.jpg)

**Comment by jeroenk22** [comment]
As you can see the form-group div of the Select2 widget has a has-succes class, but the span inside it keep a has-error class..

**Comment by kartik-v** [comment]
This is more a Yii validation behavior and not a Select2 plugin issue. But the problem is Yii client validation does not understand the Select2 markup like normal inputs.

I have provided an enhancement specific to Select2 widget that will fix it for most use cases. 

However for advanced cases like AJAX based validations in Select2 - you need to write the JS code and trap this in the right event (e.g. on form submit button click ) and use the `initS2Change` JS method and pass the `$("#your-select2-id")` as a parameter to the above method
