### ISSUE TITLE
When a select2 element gains focus, typing should start searching

### ISSUE THREAD

**Issue by michaelarnauts** [kartik-v/yii2-widget-select2#174]
When the element has a focus by tabbing into it, you can't start typing. This is useful when completing address information for example.

I think when the element has focus, and a keypress (except tab, enter, ...) occurs, it could automatically open the dropdown and start searching. This way, you don't need to click the element to open it and start searching.

**Comment by kunjirsantosh** [comment]
I have same issue "When the element has a focus by tabbing into it, you can't start typing" . please help.
