### ISSUE TITLE
Select2 Kartik

### ISSUE THREAD

**Issue by AditMulyadi** [kartik-v/yii2-widget-select2#176]
select2 search kartik why not functioning at the time was in a popup bootstrap
![untitled](https://cloud.githubusercontent.com/assets/20674084/18379839/bac60270-769e-11e6-87ce-b75e8ddedad5.png)

**Comment by diegomes** [comment]
It's a problem with modal property tabindex -1. Change this property to 0 and will work fine.
.

**Comment by kartik-v** [comment]
yes please go through docs and demos in detail and check the [example demos](http://demos.krajee.com/widget-details/select2) where this has been mentioned.

**Comment by AditMulyadi** [comment]
thanks for the help, now my select2 widget is already well underway
