### ISSUE TITLE
reload select2 with pjax

### ISSUE THREAD

**Issue by akorinek** [kartik-v/yii2-widget-select2#18]
I've embedded a select2 field inside of a pjax container. The idea is to refresh the list of options without reloading the entire form (the user has an "add" button to add more options to the select list). The pjax reload works, but then the widget only shows a reloading rotating arrow, it is not fully rendered after the pjax refresh. I'm guessing that some js event is also necessary to complete the reload. Can you please advise how to get this working?
Alternatively, would using the ajax feature be a better idea than what I described above?

Thanks.

**Comment by akorinek** [comment]
Solved problem by using id parameter in Pjax widget instead of creating my own <div> container

**Comment by Zmey2701** [comment]
Hi. I'm using the widget with ActiveForm like in the demo examples on your page. But when I submit the form and get it reloaded, the select2 fields are spinning all the time. The fields are not loaded completely as full pretty Select2. In returned page code I see just an input with value. I can see the id I've selected by value before through the 'pluginLoading' => false -- in this case the  field is displayed as simple input with Id of previously selected item.
I've just thought it looks like the same issue. Could you describe the answer you found out more completely?

Thanks.
