### ISSUE TITLE
Use of "matcher" for search in Optgroup

### ISSUE THREAD

**Issue by lugaru90** [kartik-v/yii2-widget-select2#181]
Hey all,

how can i use the "matcher" function of select2 v4 with your Version.  Tried it with:

``` js
'pluginOptions' => [
  'matcher' => 'matchGroup'
]
```

But gives error, that matcher is not defined. I need it for searching in the optgroupNames.

Cheers

**Comment by bbszabi** [comment]
You have to use JsExpression, like this:
'pluginOptions' => [
  'matcher' => new JsExpression('matchGroup')
]

**Comment by yii2backendwebdeveloper** [comment]
Not working ``select2.full.js?v=1620807619:3467 Uncaught TypeError: matcher is not a function``

**Comment by Spillo89** [comment]
have the same problem

`Uncaught TypeError: matcher is not a function`
