### ISSUE TITLE
Uncaught ReferenceError: select2_d4726750 is not defined

### ISSUE THREAD

**Issue by acoman-ro** [kartik-v/yii2-widget-select2#182]
I'm using a function that renders 3 select2 inputs (country, state, city). State and city are DepDrops and the only select that gives error is he country one (the first one). I have a platform with 5 themes and I call the same function on all 5 but on one of them it gives me this error.

![Image1]
(https://puu.sh/s2bGd/b26df00c8c.png)

![Image2]
(https://puu.sh/s2bzg/c6ac7ff422.png)

I've tried every possibility that came into my mind and I can't make it work.

**Comment by new9xgh** [comment]
you can see  https://github.com/kartik-v/yii2-widget-select2/issues/211
