### ISSUE TITLE
issue with tags

### ISSUE THREAD

**Issue by albertborsos** [kartik-v/yii2-widget-select2#184]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. use with a model with any attribute
2. paste the following snippet to your form
```php
<?= $form->field($model, 'quick_replies')->widget(\kartik\select2\Select2::className(), [
    'data' => $model->getQuickRepliesToSelect2(), // empty array
    'options' => [
        'multiple' => true,
    ],
    'pluginOptions' => [
        'tags' => true,
        'minimumInputLength' => 1,
        'tokenSeparators' => [',', ' '],
    ],
]) ?>
```
3. reload the form

## Expected behavior and actual behavior

When I follow those steps, I see that  after the second item the first 2 disappear: 
![select2 1](https://cloud.githubusercontent.com/assets/7307145/20066273/47a7e730-a511-11e6-8f67-2e3d7556cb4e.gif)

I was expecting it does not disappear.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer (not tested)
- [x] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.4
- yii2-widget-select2 version: *@dev

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by albertborsos** [comment]
This one is OK, but i need to write the surrounding template, and the validation does not work.
```php
        <?= \kartik\widgets\Select2::widget([
                    'id' => Html::getInputId($model, 'quick_replies'),
                    'name' => Html::getInputName($model, 'quick_replies'),
                    'options' => [
                        'multiple' => true,
                    ],
                    'value' => $model->getQuickRepliesToSelect2(),
                    'data' => [],
                    'pluginOptions' => [
                        'tags' => true,
                        'allowClear' => true,
                        'minimumInputLength' => 1,
                        'tokenSeparators' => [',', ' '],
                    ],
                ]) ?>
```

**Comment by kartik-v** [comment]
Not completely clear with how you are rendering the HTML markup. It seems you may have duplicate identifiers (HTML `id` attribute) for select2 widget input on the same page which would cause the plugin to break and you need to keep it unique.

For example tagging similar to your code works on the [demo page here](http://demos.krajee.com/widget-details/select2#usage-tags).

**Comment by albertborsos** [comment]
No, there is only one id.
On the demo page there is an example with static widget. But i have issue when i use with `ActiveForm` instance like `$form->field($model, 'attribute')->widget(Select2::className(), $config)`

I will make a live example later.

**Comment by kartik-v** [comment]
The first example on the [demo page for tags usage](http://demos.krajee.com/widget-details/select2#usage-tags) is a widget with model and active form.

**Comment by albertborsos** [comment]
OK, I found it. There was a trim filter in the model's rule method. After I removed it, then the widget starts working as expected.
