### ISSUE TITLE
Dependent Select2

### ISSUE THREAD

**Issue by vilaskrish** [kartik-v/yii2-widget-select2#188]
I would like to use dependent select2 option in my project as follows.
![dependent](https://cloud.githubusercontent.com/assets/24294507/21477382/4bc91326-cb67-11e6-83bf-cf612fa4190d.PNG)
![controller](https://cloud.githubusercontent.com/assets/24294507/21477414/b2560612-cb67-11e6-9f2e-b3a0606730fb.PNG)
![view](https://cloud.githubusercontent.com/assets/24294507/21477420/ba33801c-cb67-11e6-9d26-3ffbeac3e638.PNG)

Can u help me how to do this..

**Comment by vilaskrish** [comment]
got the solution thank you

**Comment by JeremiahSeagraves** [comment]
Which was the solution, I need to pick 
a Country, then 
any number of states, then the 
any number of cities in those states
