### ISSUE TITLE
Please create tag 2.0.9 to allow to use it with composer.

### ISSUE THREAD

**Issue by nagyt234** [kartik-v/yii2-widget-select2#190]
Please create tag 2.0.9 to allow to use it with composer.

**Comment by michaelarnauts** [comment]
Isn't 2.0.9 final yet?

**Comment by IgorCode** [comment]
According to change log it is, but there is no tag/release for 2.0.9 -> https://github.com/kartik-v/yii2-widget-select2/releases

**Comment by lubosdz** [comment]
As of 2017/04 - (10 months since stable 2.0.9 release) composer still tags latest stable `2.0.8`. The `2.0.9` is only possible with `@dev ` tag, which makes full git repo checkout - makes vendor directory dirty & slows installation down. Pls fix ...

**Comment by kartik-v** [comment]
done
