### ISSUE TITLE
Kartik dependend dropdown

### ISSUE THREAD

**Issue by aju003** [kartik-v/yii2-widget-select2#193]
I am using the Kartik Depdrop widget. I want to display the already selected value in dependend dropdown while updating. Anyone help me?

**view Page**

<?=  $form->field($a, 'to')->label(false)->widget(Select2::classname(), [
                'data'          => $quotation_plan->placeNameArray,
                'language'      => 'en',
                'options'       => ['placeholder' => 'Select ...','class'=>'plan','id'=>'to_'.$count,],
                'pluginOptions' => ['allowClear' => true,'width' => '200px']
                ]);
            ?>
`

<?=
                $form->field($a, 'category')->widget(DepDrop::classname(), [
                  'options'       => ['id' => 'category_'.$count,'class'=>'plan form-control',],
                  'type' => DepDrop::TYPE_SELECT2,
                  'pluginOptions' => [
                      'depends'     => ['staytype_'.$count,],
                      'placeholder' => 'Select...',
                      'url'         => Url::to(['/quotations/quotations/hotel?val='.$count.'_'.$a->to]),
                      'params'=>[$a->category],
                  ]
              ])->label(false);
            ?>

- 

**controller**

public function actionHotel($val)
    {
        $out = [];
        $a=explode('_',$val);
        $category_id =$_POST['depdrop_all_params']['staytype_'.$a[0]];
        $hotels = Hotels::find()->where(['place_id' => $a[1],'category_id' => $category_id])->all();
         foreach ($hotels as $id => $post) {
              $out[] = ['id' => $post['id'], 'name' => $post['name']];
         }
         echo Json::encode(['output' => $out, 'selected' => '']);
}

**Comment by shyamsasit** [comment]
`echo $form->field ($model_Estclaims, 'ClientCompanyId')->widget (Select2::classname (), ['options' => ['id' => 'estclaims-clientcompanyid', 'required' => 'required'], 'data' => $array2])->label (false);


                       echo     Html::hiddenInput('input-type-1', $model_Estclaims->ClientUserId, ['id'=>'input-type-1']);

                   echo     $form->field ($model_Estclaims, 'ClientUserId')->widget (DepDrop::classname (), [

                            'options' => ['placeholder' => 'Select ...', 'required' => 'required'], 'type' => DepDrop::TYPE_SELECT2,

                            'select2Options' => ['pluginOptions' => ['allowClear' => true]], 'pluginOptions' => ['depends' => ['estclaims-clientcompanyid'], 'url' => Url::to (['/site/clients-filter']),'params'=>['input-type-1', 'input-type-2'],

                                  'initialize' => true, 'initDepends' => ['estclaims-clientcompanyid'], 'loadingText' => 'Loading Adjuster...',]])->label (false);

                       `
controller
`function actionClientsFilter() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $cat_id = $parents[0];
                $query = new Query();
                $query->select ()->all ();
                $command = $query->createCommand ();
                $list = $command->queryAll ();
                $param1 = null;
                $param2 = null;
                if (!empty($_POST['depdrop_params'])) {
                    $params = $_POST['depdrop_params'];
                    $param1 = $params[0]; // get the value of input-type-1

                }

                $selected = null;
                
                    foreach ($list as $i => $account) {
                        $out[] = ['id' => $account['user_id'], 'name' => $account['first_name'] . ' ' . $account['last_name']];
                        if ($account['user_id'] == $param1) {
                            $selected = $account['user_id'];
                        }
                    }
                 
          
                // the getDefaultSubCat function will query the database
                // and return the default sub cat for the cat_id

                echo Json::encode(['output'=>$out, 'selected'=>$selected]);
                return;
            }
        }
        echo Json::encode(['output'=>'', 'selected'=>'']);
    }`

**Comment by aju003** [comment]
thanks. @shyamsasit
