### ISSUE TITLE
Kartik dependent dropdown

### ISSUE THREAD

**Issue by aju003** [kartik-v/yii2-widget-select2#194]
May I use dependent dropdown which depends on another two dropdowns?

eg: 
I have Dropdown1 and Dropdown2

I want to create Dropdown3 depends on Dropdown1 and Dropdown2.

**Comment by metola** [comment]
This call [depdrop.](https://github.com/kartik-v/yii2-widget-depdrop)

**Comment by kartik-v** [comment]
Yes use the [DepDrop widget based on dependent-dropdown plugin](http://demos.krajee.com/widget-details/depdrop).

**Comment by favourkiiza** [comment]
How come it has some issues with current yii2 version. It only displays blank space in the dependent dropdown
