### ISSUE TITLE
[request:] Enhance AJAX-optgroups usage documentation/example

### ISSUE THREAD

**Issue by amlopezalonso** [kartik-v/yii2-widget-select2#199]
Hi Kartik,

Please, could you expand examples/documentation on using optgroups in AJAX cases? I feel some parts lack detail level.

For instance, it is said that `data`could be fed with `ArrayHelper::map` in order to use sub-arrays, but on the contrary to a normal dropDown operation where having optgroups is as simple as doing in model:

    public function getBibliographyList()
    {
        return ArrayHelper::map(Bibliography::find()->select(['id','title','author'])->orderBy('author','title')->all(), 'id', 'title', 'author');
    }

in Select2 there are some issues that complicate the process as having special hardcoded attributes like `text`, `children`, etc. which I'm not sure how to integrate in the widget params in order to show optgroups in dropdown as you do in several examples.

It would be nice if you could demonstrate how server/client-side code works in these AJAX cases.

Big thank you for all your work

**Comment by amlopezalonso** [comment]
I'm posting my approach just in case:

[http://stackoverflow.com/questions/42331110/yii2-how-to-use-option-groups-with-ajax-based-kartiks-select2](url)

**Comment by kartik-v** [comment]
It is standard to a yii2 generated data by ArrayHelper::map as you mentioned. The data with optgroups must return an output like below:

```php
$data = [
"Alaskan/Hawaiian Time Zone" => [
    "AK" => "Alaska",
    "HI" => "Hawaii",
],
"Pacific Time Zone" => [
    "CA" => "California",
    "NV" => "Nevada",
    "OR" => "Oregon",
    "WA" => "Washington",
],
"Mountain Time Zone" => [
    "AZ" => "Arizona",
    "CO" => "Colorado",
    "ID" => "Idaho",
    "MT" => "Montana",
    "NE" => "Nebraska",
    "NM" => "New Mexico",
    "ND" => "North Dakota",
    "UT" => "Utah",
    "WY" => "Wyoming",
];
```

**Comment by kartik-v** [comment]
Such a format like above has been used in [Select2 widget examples](http://demos.krajee.com/widget-details/select2#usage-basic)

**Comment by amlopezalonso** [comment]
If you wish so, I could elaborate my example above a bit further. Just suggest me the way it should be done as I'm not familiar with github way of doing things.
