### ISSUE TITLE
Cannot Install 1.1.0 via Composer

### ISSUE THREAD

**Issue by RamzyVirani** [kartik-v/yii2-widget-select2#20]
Hi Kartik,
First of all, thanks for these useful plugins and widgets. I am trying to update from 1.0.0 to 1.1.0 in my application via composer, but its not updating the script files.

I am very new to composer and repositories, Correct me if I am wrong, but i think you need to release the latest version of your repository.

**Comment by kartik-v** [comment]
There is no version 1.1.0 . There is a release 1.0.1.

But its been superseeded with release v2.0.
