### ISSUE TITLE
Language problem - sr-Latn

### ISSUE THREAD

**Issue by tigrasti** [kartik-v/yii2-widget-select2#200]
I searched issues, there are smoe similiar problems, but can't find the general solution. 
In config file, as default language is set 'sr-Latn', and when I change to 'en', everything is ok, and select2 load all data correctly. But when I return to 'sr-Latn', widget looks like loading data. 
![image](https://cloud.githubusercontent.com/assets/8338363/23505751/57f460bc-ff45-11e6-883a-cef7a5f8111c.png)
and in console there is showing error like this.
![image](https://cloud.githubusercontent.com/assets/8338363/23505789/7a9170a6-ff45-11e6-9af5-fbeab1da4fb0.png)
What can do to fix that problem?

**Comment by kartik-v** [comment]
The console log is showing error in `redactor.js` and not select2 ... so you need to check your other plugins like redactor which is causing this error.
