### ISSUE TITLE
Select2 validation

### ISSUE THREAD

**Issue by pptyasar** [kartik-v/yii2-widget-select2#203]
## Steps to reproduce the issue

This bug  is select2 tag
1.Select the dropdown value 
2.Insert new tag value

Now validation will not work

If doing like in this order validation is working
1.Insert new tag value
2.Select the dropdown value 

## Expected behavior and actual behavior

When one attribute has validation rules its not working.
Ex: If one field have validation rule of email

It is working when tag is inserting at first (Without selected dropdown See image 1)

When any of dropdown selected then new tag value is  not validating ( See image 2
![screenshot1](https://cloud.githubusercontent.com/assets/21305090/23823227/1216c828-0684-11e7-9e57-6652082fbd74.png)
![screenshot2](https://cloud.githubusercontent.com/assets/21305090/23823229/1647f822-0684-11e7-927b-05a5953c8b89.png)

)

## Environment

Browsers

- [x] Google Chrome

Operating System

- [x] Linux

Libraries

- jQuery version:  2.2.4
- yii2-widget-select2 version: dev-master e135c25

**Comment by alejosv** [comment]
Same issue, but with select option default, same validation rules, different behaivor.
