### ISSUE TITLE
Ajax search and results with optgroup

### ISSUE THREAD

**Issue by CristianTan** [kartik-v/yii2-widget-select2#21]
Hello,

Is there any way to use the ajax search, and return the results with an optgroup, to have the result displayed similar to the normal select2 dropdown (in your examples you have the states optgroups).

Could find anything to work.

Thanks!

**Comment by kartik-v** [comment]
You can do even better with the latest release (v2.0) by advanced formatting of your results.

Check [this example for ajax based search with templating to format results](http://demos.krajee.com/widget-details/select2#usage-templates).
