### ISSUE TITLE
select all on widget, when data is brought by ajax

### ISSUE THREAD

**Issue by handrei** [kartik-v/yii2-widget-select2#210]
hey, i'm having an issue with select all on widget, when data is brought by ajax.
does anyone is having this issue ? or i'm not using this widget how i'm supposed to :)

hope is ok posting here.
thanks,
handrei.

**Comment by DrmagicE** [comment]
try https://github.com/kartik-v/yii2-widget-select2/pull/236

**Comment by vadim-bulochnik** [comment]
@DrmagicE doesn't works.
