### ISSUE TITLE
The select2 is not working in ie8 

### ISSUE THREAD

**Issue by merlano17** [kartik-v/yii2-widget-select2#22]
It keeps on showing a loading gif nothing else

**Comment by kartik-v** [comment]
Check which version of jquery you have on your machine?

Most modern plugins or updates may use jquery 2.0 and above - which does not support IE8... [read jquery drops support](http://www.infoworld.com/article/2614553/javascript/jquery-2-0-drops-support-for-old-versions-of-internet-explorer.html).

**Comment by merlano17** [comment]
The default select2 is working in ie8

**Comment by kartik-v** [comment]
You can check with updated code now...

**Comment by merlano17** [comment]
Thanks for the fix bro, its working, but now the problem is for some reason your select2 is not getting updated. i manually updated the select2-kv.js file and it worked, its not getting updated in composer update. My composer config is "kartik-v/yii2-widgets": "@stable"

**Comment by merlano17** [comment]
Am always getting updated to this commit only 890e3055d1803e74b325cf8838908b4334d993ac

**Comment by kartik-v** [comment]
It maybe due to a composer issue of updating packages on your environment. [Follow this webtip](http://webtips.krajee.com/composer-fails-update-vendor-packages/) to refresh your composer packages.

**Comment by merlano17** [comment]
That commit you didnt make as a release so only its not getting updated.

**Comment by kartik-v** [comment]
The [release v1.0.1 is already tagged here](https://github.com/kartik-v/yii2-widget-select2/releases/tag/v1.0.1) with the latest code. Not sure what is your issue.

**Comment by merlano17** [comment]
anyway i did to "kartik-v/yii2-widget-select2": "dev-master" and it works.
