### ISSUE TITLE
Load assets from CDN

### ISSUE THREAD

**Issue by robov** [kartik-v/yii2-widget-select2#223]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- yii2-widget-select2 version:

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by robov** [comment]
How can I load the required js assets from a CDN ?
To speed up my site loading select2.js and select2-krajee.js from a CDN would increase in must faster response times

**Comment by MartinKolarik** [comment]
You can use https://www.jsdelivr.com/package/npm/select2 and https://www.jsdelivr.com/package/gh/kartik-v/yii2-widget-select2

**Comment by robov** [comment]
Thanks... but where do I specify that ?

Like my bootstrap in main.php
```
            'bundles' => [
//                // use bootstrap css from CDN
                'yii\bootstrap\BootstrapAsset' => [
                    'sourcePath' => null,   // do not use file from our server
                    'css' => [
```
or do I need to create a new asset file and load that somehow ?

**Comment by kartik-v** [comment]
This is a piece of cake to do in Yii 2. Just override your asset bundle in your yii2 application config as mentioned [in this customizing asset bundle guide for Yii 2](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#customizing-asset-bundles).

**Comment by robov** [comment]
Thanks... apparently I am still doing something not quite right, as I get a select2 is not a function

The original working code loads the local assets
```
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="/assets/46aff460/js/select2.full.js"></script>
<script src="/assets/46aff460/js/select2-krajee.js"></script>
```

When I try to override with
```
            'kartik\select2\Select2Asset' => [ 
                'sourcePath' => null,   // do not publish the bundle
                'js' => [ 
                    'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js',
                    'https://cdn.jsdelivr.net/gh/kartik-v/yii2-widget-select2@2.1.0/assets/js/select2-krajee.min.js',
                    
                    ] 
            ],
```

The the code loads
```
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/kartik-v/yii2-widget-select2@2.1.0/assets/js/select2-krajee.min.js"></script>
```
But then I get a error "VM1202:2 Uncaught TypeError: jQuery(...).select2 is not a function" when I try to use select2 in my modal (with the original code it works like a charm... just slow loading....

Any suggestions ?
