### ISSUE TITLE
Select all 

### ISSUE THREAD

**Issue by SSashiBala** [kartik-v/yii2-widget-select2#226]
While selecting all values, now it is showing all values .
It will be good, if is will display as "all selected" or "{count} selected".
Please consider this issue.

**Comment by kartik-v** [comment]
Sorry this is out of scope of this widget and should be a plugin functionality or you have to write your own JAVASCRIPT to show hide some elements.

The select all functionality has just been added in this widget to help you accelerate the selection of all items.
