### ISSUE TITLE
Select if exists, create if not

### ISSUE THREAD

**Issue by Benn** [kartik-v/yii2-widget-select2#227]
Hi Kartik,
I'm wondering if it would be easy/possible to add a feature to the widget which would allow the user to add a custom value to the select.
For example, if the form is used to select a car model from a database table, to allow the user to add one that is non existant in the database.
Thanks in advance.

Cheers

Benn

**Comment by kartik-v** [comment]
You may want to go through the docs. You would need to use the tagging feature. Its [demonstrated in the documentation here and ability to add one's own tags](http://demos.krajee.com/widget-details/select2#usage-tags).

You need to code your application form and write the server code to populate these additional values into the database.

**Comment by Benn** [comment]
Thanks for taking the time to reply to what turned out to be a stupid
question.

Cheers

Benn

2017-09-16 8:13 GMT+02:00 Kartik Visweswaran <notifications@github.com>:
