### ISSUE TITLE
array_combine(): Both parameters should have an equal number of elements

### ISSUE THREAD

**Issue by nageennayak11** [kartik-v/yii2-widget-select2#228]
## Prerequisites

I have got the issue when i have update karthik plugin in yii2,
Error is :- "array_combine(): Both parameters should have an equal number of elements"
## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- yii2-widget-select2 version:

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by Krystian95** [comment]
I'm having the same issue...

**Comment by kartik-v** [comment]
please elaborate on the issue with details to reproduce your use case consistently

**Comment by nageennayak11** [comment]
First:
select2 page jumps to top when clicking drop down list of single at very first time not for multiple.

Second : 
so i just update my plugin and then get the issue array_combine():

**Comment by kartik-v** [comment]
Sorry - cannot understand the issue as it lacks details. As mentioned, could you please share steps to clearly reproduce your issue?

You could see the various examples for the usage of the extension [on the demos page](http://demos.krajee.com/widget-details/select2) ... where the issue cannot be reproduced. Compare and let know.

**Comment by timmy78** [comment]
It happens when it is a "multiple" input with a string value, not an array.

You have to use it properly like it : 

```
$form->field($model, 'ids[]')->widget(Select2::class, [ //The ids attribute should be an array of keys
            'initValueText' => [1 => 'test'], //Here an array
            'options' => [
                'value' => $model->ids, //Important and should be an array of keys
                'multiple' => true
            ],
            ...
```

**Comment by whmemon** [comment]
It Worked ! @nageennayak11 #228

**Comment by kartik-v** [comment]
Yes a multiple select input obviously expects an array value
