### ISSUE TITLE
How to add data- attribute in each option tag ?

### ISSUE THREAD

**Issue by FaizalAmiruddinR2** [kartik-v/yii2-widget-select2#235]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [ ] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

I need to use data- attribute for use another jQuery plugin, the plugin request data attribute for each options for example :
`<option data-name="Name" data-address="Address" value="1">Person Name</option>`

## Expected behavior and actual behavior

I read the documentation and I can't find option for do that.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- yii2-widget-select2 version:

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Set `Select2::options['options']` ...

for example check the second example in the [Select2 documentation - advanced example demo](http://demos.krajee.com/widget-details/select2#usage-advanced) - it shows how you can set `disabled` attribute for each option... you can similarly set other HTML attributes.

**Comment by FaizalAmiruddinR2** [comment]
Okay Thanks a lot
