### ISSUE TITLE
how to Change select2 ajax url Dynamically

### ISSUE THREAD

**Issue by dfayziev** [kartik-v/yii2-widget-select2#239]
I have select2 with 

   echo $form->field($model, 'name')->widget(Select2::classname(), [
                'initValueText'=> $name,
                'options' => [
                    'multiple' => true
                ],
                'pluginOptions' => [
                    'allowClear' => true,
                    'minimumInputLength' => 2,
                    'language' => [
                        'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
                    ],
                    'ajax' => [
                        'url' => Url::to(['datas/list']),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }')
                    ],
                    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                    'templateResult' => new JsExpression('function(data) { return data.text; }'),
                    'templateSelection' => new JsExpression('function (data) { return data.text; }'),
                ], 
     ]);
    
     **here i set the url for ajax request.**
                   ` 'ajax' => [
                        'url' => Url::to(['datas/list']),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }')
                    ],`

    How to change ajax url dynamically in javascript with some condition?
    **I want two select2 first for countries list, second for regions list of selected country
    When i choose some country i must change url of second select2 to get all region for this country**
>  In documentation I could not find a solution to the problem
    Thank you in advance!

**Comment by kartik-v** [comment]
You need to write your own javascript code for your app design to change and re-initialize the select2 plugin with the right ajax url. Closing this here as it is out of scope of this extension. Since this is application programming related - suggest to post in the discussions and comments section in the demos pages to see if you can get help from others. Also it is more related to you using javascript code for the select2 JS plugin - so it may help to reach out to that community.

**Comment by dfayziev** [comment]
Karik thank you very much !

**Comment by MadHarper** [comment]
`'ajax' => [
                    'url' => new JsExpression('foo'),
                    'dataType' => 'json',
                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
]`

And js func:

`<?php
$script = <<< JS
    
    function foo(){
        if($("#with").is(":checked")){
            return "/agreement/side/searchid-history";
        }else{
            return "/agreement/side/searchid";
        }
}
JS;
$this->registerJs($script, yii\web\View::POS_HEAD);
?>`
