### ISSUE TITLE
Even after the new release in ie8 it comes the same way it keeps loading

### ISSUE THREAD

**Issue by merlano17** [kartik-v/yii2-widget-select2#24]
![bug ie8](https://cloud.githubusercontent.com/assets/4918935/7452358/2b7e1f16-f27a-11e4-8a04-15463bc1ae2d.png)

Please have a look at it

**Comment by kartik-v** [comment]
The demo site is not updated with latest release yet.

You may update your installation with the latest widget release and try it out.

Will update the demo site when I get time.

**Comment by merlano17** [comment]
i tried in my app it gives me the same error. Uploading the pic here
![bugie8select2](https://cloud.githubusercontent.com/assets/4918935/7453596/7e9b36ee-f288-11e4-857a-55b854503168.png)

**Comment by kartik-v** [comment]
Ensure you have the updated code - (no caching problems) -- by cross checking the JS files.

This has been tested to work fine from here.

**Comment by merlano17** [comment]
I tired clearing the cache and even updated your widget

**Comment by kartik-v** [comment]
It seems your extension is not updated for some reason to latest. Do cross check with source and try.

You can cross check now the demo site - its now upgraded to the latest extension version and does display fine on IE8 - with however downgraded functionality (like certain CSS3 styles that are not supported in IE8).
