### ISSUE TITLE
Losing focus after selecting an item

### ISSUE THREAD

**Issue by et-nik** [kartik-v/yii2-widget-select2#240]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

I don't use mouse. Use only TAB, ↓, ↑ and ENTER keys.

1. Select items using ↓ or ↑ keys
2. Press Enter after selection element
3. You will lose focus from current select element

This bug missing in original Select2 plugin.

![krajee-select2-bug](https://user-images.githubusercontent.com/3670640/33218490-3192511e-d14e-11e7-9da5-e9004b91de26.gif)

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox

Operating System

- [x] Linux

## Isolating the problem

- [x] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is because the latest plugin version has not been updated on this repo (repo has v4.0.3 of the plugin while the source plugin is now into v4.0.6 rc). I will be merging the latest plugin code into this repo shortly.

**Comment by kartik-v** [comment]
Resolved via [update to release v3.1.1](https://github.com/kartik-v/yii2-widget-select2/commit/033c8199174e06368bac683788b28b6e929246c9).
