### ISSUE TITLE
Incorrect processing of model attributes

### ISSUE THREAD

**Issue by pitonn** [kartik-v/yii2-widget-select2#243]
Hi. Select2 treats the same attributes name of the model in a strange way:
I expect to get first "checkboxList" and then "Select2 widget", but instead "checkboxList" turn to dropdown and "Select2 widget" become invisible. How fix it? Tnx.

`<?= $form->field($model, 'regions')->checkboxList([0=>'test1', 1=> 'test2']) ?>`
`<?= $form->field($model, 'regions')->widget(Select2::className(), [])->label(false) ?>`

getting html result:

\<div class="form-group field-advcampaign-regions">
&nbsp;&nbsp;\<label class="control-label">Регионы\</label>
&nbsp;&nbsp;\<input type="hidden" name="AdvCampaign[regions]" value="">
&nbsp;&nbsp;\<div id="advcampaign-regions" tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
&nbsp;&nbsp;&nbsp;&nbsp;\<div class="checkbox">\<label>\<input type="checkbox" name="AdvCampaign[regions][]" value="0"> test1\</label>\</div>
&nbsp;&nbsp;&nbsp;&nbsp;\<div class="checkbox">\<label>\<input type="checkbox" name="AdvCampaign[regions][]" value="1"> test2\</label>\</div>
&nbsp;&nbsp;\</div>
&nbsp;&nbsp;\<span class="select2 select2-container select2-container--krajee select2-container--below select2-container--focus" dir="ltr" style="width: 100%;">
&nbsp;&nbsp;&nbsp;&nbsp;\<span class="selection">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-advcampaign-regions-container">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<span class="select2-selection__rendered" id="select2-advcampaign-regions-container">\</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<span class="select2-selection__arrow" role="presentation">\<b role="presentation">\</b>\</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\</span>
&nbsp;&nbsp;&nbsp;&nbsp;\</span>
&nbsp;&nbsp;&nbsp;&nbsp;\<span class="dropdown-wrapper" aria-hidden="true">\</span>
&nbsp;&nbsp;\</span>
&nbsp;&nbsp;\<p class="help-block help-block-error">\</p>
\</div>

\<div class="form-group field-advcampaign-regions">
&nbsp;&nbsp;\<select id="advcampaign-regions" class="form-control" name="AdvCampaign[regions]" data-s2-options="s2options_d6851687" data-krajee-select2="select2_5aa3bfcf" style="display:none">\</select>
&nbsp;&nbsp;\<p class="help-block help-block-error">\</p>
\</div>

**Comment by kartik-v** [comment]
You obviously should not be having the same attribute names rendering on the page like that in that way - because both of them will create elements with duplicate HTML ID (which is broken or unsupported by HTML standards).

If you are still keen to render the same name attributes... set their `options['id']` property to different unique values.
