### ISSUE TITLE
Select/deselect all not functional

### ISSUE THREAD

**Issue by digitv** [kartik-v/yii2-widget-select2#246]
Hello!
There is a bug with latest version of plugin. If you are using "templateResult" callback for list html code generation (select>option inner html differs from html inside ul>li element) "Select/deselect all" options is not functional.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- Google Chrome
- Mozilla Firefox

Operating System

- Linux

Libraries

- jQuery version: 3.2.1
- yii2-widget-select2 version: 2.1.1

## Isolating the problem

- The bug happens consistently across all tested browsers
- This bug happens when using yii2-widget-select2 without other plugins

**Comment by kartik-v** [comment]
Fixed via latest update to release v2.1.2
