### ISSUE TITLE
Regular Loading 

### ISSUE THREAD

**Issue by gaurabhi** [kartik-v/yii2-widget-select2#250]
I'm using Admin LTE Template. Everything is working fine but i'm not able to use your widgets. In Select2 it always shows loading 
**Files Included** 
![file include](https://user-images.githubusercontent.com/36297855/36025322-a5050ab4-0db8-11e8-9ca1-840f8b7b2d5d.PNG)
**View Form** 
![regular loading](https://user-images.githubusercontent.com/36297855/36025106-e20d0746-0db7-11e8-86e1-11af3725b658.PNG)

**Control**
![control](https://user-images.githubusercontent.com/36297855/36025387-dd1cb1e0-0db8-11e8-9b9a-71e0255197e7.PNG)

**Comment by kartik-v** [comment]
Not sure of your problem (you may need to check your code). 

For styling as per AdminLTE style - set Select2 widget `theme` property to `Select2::THEME_DEFAULT`.
