### ISSUE TITLE
Unable to change 'noResults' content at initialization 

### ISSUE THREAD

**Issue by IGaMbLeRI** [kartik-v/yii2-widget-select2#251]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Setting ```language``` property to an ```array``` causes an error. Respectfully so, according to the documentation the widget will accept only a ```string```.
2. Therefore, in order to achieve the objective of changing the appearance (and functionality) of "No results found.", I attached the following JS:
```
$(".select2").select2({
    language : {
        noResults : function(params) {
            return "Some other stuff here";
        }
    }
});
```
the following option was also advised in https://github.com/select2/select2/issues/3576 : 
```
escapeMarkup: function (markup) {
    return markup;
}
```

## Expected behavior and actual behavior

When I follow those steps, I see:

Although the inserted JS did not trigger besides being correctly attached at the bottom of the page, running the JS from Console produced one aspect of the expected result.

As it turns out, running the JS will effectively reset the existing Select2 along with all data and styles, but it will also change the text of the ```noResults```! This is an expected behaviour for the Select2 plugin, but the plugin also allows to set these variables during initialization so you don't have to change them on the go.

I was expecting:

Frankly, I was expecting the Widget to accept ```array``` as ```language```, so I could in some way pass the custom ```noResults``` content, such as a button to add the Input to the Dropdown list and select that value. All that without having to recreate the widget in JS.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: v3.2.1
- yii2-widget-select2 version: v2.1.1

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by lordcroci** [comment]
I have the same problem, hope someone is gonna find a solution.. please UP!

**Comment by ilyasavitski** [comment]
Hi
Try this `'noResults' => new JsExpression("function () { return 'Something here...'; }"),`

**Comment by kartik-v** [comment]
You need to escape the JS functions via `yii\web\JsExpression` when setting key values within PHP arrays - so that they are encoded properly:

Example:

```php
'pluginOptions' => [
    'escapeMarkup' => new yii\web\JsExpression('function (markup){return markup}')
]
```

**Comment by lordcroci** [comment]
thanks a lot!
