### ISSUE TITLE
maximumSelectionLength fails with 'Select All' and subsequent 'Unselect All' results in TypeError: elemData is undefined

### ISSUE THREAD

**Issue by probkiller** [kartik-v/yii2-widget-select2#258]
## Steps to reproduce the issue

1. Setup the widget to select multiple options and set maximumSelectionLength to a number greater than the total number of options (eg 'maximumSelectionLength' => 2, and total number of options = 3)
2. Click on **Select All**
3. Then, click on **Unselect All**

## Current behavior
As evident from title, this is a combination of errors. When using **maximumSelectionLength** (maximumSelectionLength < total number of options),

1. Clicking on **Select All** selects all options.
2. After all options are selected, clicking on **Unselect All** results in - **TypeError: elemData is undefined**

## Expected behavior

For Select All, this is not clear. But, it should be one of the following:
1. Select All should not be visible when using maximumSelectionLength
2. Clicking on Select All may select first n options

For Unselect All, any currently selected options should be cleared

## Environment
- jQuery version: 2.2.4
- yii2-widget-select2 version: 2.1.2

**Comment by probkiller** [comment]
This may be related:

Once the maximum number of options have been selected, and clicking on **Select All** produces **TypeError: elemData is undefined**

**Comment by Jonyx4** [comment]
Same issue here, was this fixed?
