### ISSUE TITLE
this widget have event select2-select or select?

### ISSUE THREAD

**Issue by thuongqbd** [kartik-v/yii2-widget-select2#26]
this widget have event select2-select or select or something after select?
I used
'pluginEvents' => [
	"select"=>"function() {console.log('select'); }",
	"select2-select" => "function() { console.log('select2-select'); }",
]
but nothing show in log

**Comment by kartik-v** [comment]
Check the latest release v2.0 -- its `select2:select` for Select2 plugin release v4.0. Read the plugin docs for details on the [Select2 plugin site](https://select2.github.io/).
