### ISSUE TITLE
Treeview feature

### ISSUE THREAD

**Issue by karProgrammer** [kartik-v/yii2-widget-select2#264]
Hello @kartik-v ,
Great extension! But I think if you add the ability to display nested data like your [tree view input widget](http://demos.krajee.com/tree-manager-demo/tree-view-input) extension, it will be a great feature.
Because the tree view input widget need a lot of configurations and a specific table structure. But adding the ability to display nested data from array will be more easy.

Thank you.

**Comment by karmac2015** [comment]
How much do you want to add this feature ?
