### ISSUE TITLE
Rendering the Select2 with different class

### ISSUE THREAD

**Issue by CarlosMoralesSal** [kartik-v/yii2-widget-select2#266]
Hello @kartik-v,
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [X] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. When I render the filters in my page with 3 select2 widgets in the same li. I am using adminlte as theme and I want to work in the header section I try to see the three Select2 as follow

```
   <li class="dropdown">
       <div class="row buscadores">
                  <div class="col-xs-4">
                            <?php
                                     echo $form->field($searchModel, 'map_id')->widget(\kartik\select2\Select2::className(), [
                                    'model' => $searchModel,
                                    'data' => \yii\helpers\ArrayHelper::map(\common\models\Map:find()->where(['deleted_at'=>NULL])->orderBy('title')->asArray()->all(), 'id', 'title'),
                                    'options' => ['placeholder' => Yii::t('app', 'CHOOSE_MAP')],
                                    'pluginOptions' => [
                                    'allowClear' => true,
                                    ],
                                ]);
                              ?>
                          </div>
                          <div class="col-xs-4">
                           <?php
                                 echo $form->field($searchModel, 'country_id')->widget(\kartik\widgets\Select2::classname(), [ 
                                    'data' => \yii\helpers\ArrayHelper::map(\common\models\Country::find()->where(['type'=>Attribute::TYPE_CATEGORY,'map_id'=>Yii::$app->user->identity->map_id])->notDeleted()->isNotEntitiyType()->orderBy('name')->asArray()->all(), 'id', 'name'),
                                    'name'=> 'map_id',
                                   'options' => ['placeholder' => Yii::t('app', 'CHOOSE_COUNTRY')],
                                    'pluginOptions' => [
                                    'allowClear' => true
                                    ],
                                ]);       

                             ?>
                          </div>
                          <div class="col-xs-4">
                              <?php  echo $form->field($searchModel, 'map_attributes')->widget(\kartik\widgets\Select2::classname(), [
                                        'data' => \yii\helpers\ArrayHelper::map(\common\models\Attribute::find()->where(['type'=>\common\models\Attribute::TYPE_ATTRIBUTE,'map_id'=>Yii::$app->user->identity->map_id])->notDeleted()->isNotEntitiyType()->all(), 'uuid', 'name','parentCategory.name'),
                                        'options' => ['multiple'=>true,'placeholder' => Yii::t('app', 'CHOOSE_ATTRIBUTES')],
                                        'pluginOptions' => [
                                            'allowClear' => true,
                                        ],

                                    ]);

                              

                               ?>

                          </div>                         

                        </div>

                       </li>

```

## Expected behavior and actual behavior
I expected to have the same render view with the first and the second select2, but the second one renders with select2-container--bootstrap instead of select2-container--krajee as the first one do and it's no correct because the only thing which changes between both are data and name. 

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version:
- yii2-widget-select2 version: last one

## Isolating the problem

- [] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alko79** [comment]
same here,
it could be nice to have the possibility of have 2 instances of the widget on the same model selection.
like:
<h3>Customer 1</h3>
$form->field($model, 'cust_id')->widget(Select2::classname(), [
  'data' => ArrayHelper::map(Customer::find()->orderBy('name')->all(), 'id', 'name', 'company'),
  'options' => ['placeholder' => 'select customer'],
  'pluginOptions' => ['allowClear' => true],
]);
<h3>Customer 2</h3>
$form->field($model, 'cust_id')->widget(Select2::classname(), [
  'data' => ArrayHelper::map(Customer::find()->orderBy('name')->all(), 'id', 'name', 'company'),
  'options' => ['placeholder' => 'select customer'],
  'pluginOptions' => ['allowClear' => true],
]);

in this case the widget only render the first one.
it should be useful being able to specify the class to be created in JS code directly into definition
like:
...widget(Select2::classname(['cust1'])...
in this way when the JS code is generated the 2 instances will be rendered.

is that possible to achive out of source code?
any kartik guru here for the rescue?

**Comment by kartik-v** [comment]
@CarlosMoralesSal  you need to set the `Select2::theme` property. Check [docs and examples](http://demos.krajee.com/widget-details/select2#settings) .

@alko79 - you need to set `Select2::options['id']` to a unique value in case you are rendering the same model attribute twice on the same page.
