### ISSUE TITLE
remove select2-krajee.css

### ISSUE THREAD

**Issue by ered15** [kartik-v/yii2-widget-select2#267]
quick question, is there any way to remove select2-krajee.css from loading, I tried :
```
'kartik\select2\Select2Asset' => [
                    'css' => [],
                ],
```
but it wont remove it.

**Comment by ered15** [comment]
nevermind, found out the solution:

```
'kartik\select2\ThemeKrajeeAsset' => false,
'kartik\select2\Select2Asset' => [
  'css' => [],
],
```

**Comment by kartik-v** [comment]
That is not the correct way.

You just need to set / override the `Select2::theme` property. It defaults to `Select2::THEME_KRAJEE` - which can be changed to `Select2::THEME_DEFAULT` to load the default theme for example.
