### ISSUE TITLE
Select2Asset with bootstrap4

### ISSUE THREAD

**Issue by sgatrip** [kartik-v/yii2-widget-select2#269]
we use 'kartik\select2\Select2Asset', in our Yii 2 + bootstrap4 env.

Problem : Select2Asset load the bootstrap 3 css version.

How to change Select2Asset to use bootstrap4 ?

We have tried to use 'kartik\select2\ThemeKrajeeBs4Asset',  but no success.

Regards

**Comment by kartik-v** [comment]
Set `Select2::bsVersion` to `4.x` and install 'yiisoft\yii2-bootstrap4`  and load bootstrap 4 css/js in your views. There will be updates to demo site shortly to move to BS4.
