### ISSUE TITLE
Select2 4.0.0

### ISSUE THREAD

**Issue by kevin-brown** [kartik-v/yii2-widget-select2#27]
Just a heads up, Select2 4.0.0 was released about two weeks ago.

**Comment by kartik-v** [comment]
Thanks. Will be updating this to latest release.

**Comment by kartik-v** [comment]
Enhancement request as in kartik-v/yii2-widgets#252.

**Comment by kartik-v** [comment]
Resolved via d2b020.

**Comment by kartik-v** [comment]
Resolved via d2b0200.
