### ISSUE TITLE
Select2 becomes un-reopnsive when used with jquery.steps

### ISSUE THREAD

**Issue by buttflattery** [kartik-v/yii2-widget-select2#270]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Install Select2 and include inside the html that is used as the basic template for steps
```
<div id="my-container">
    <h3>Keyboard</h3>
    <section>
echo Select2::widget([
    'name'=>'test',
    'data' => [0 => 'No', 1 => 'Yes'],
    'options' => [
        'class' => 'form-control',
    ],
    'theme' => Select2::THEME_BOOTSTRAP,
    'pluginOptions' => [
        'allowClear' => true,
        'placeholder' => 'Select Status',
    ],
]);
    </section>
    <h3>Effects</h3>
    <section>
        <p>Wonderful transition effects.</p>
    </section>
</div>
```
2.Initialize the jquery.steps.js script with minimal configurations
```
$('#my-container').steps({
         headerTag: 'h2',
         bodyTag: 'section',
         transitionEffect: 'slideLeft',
 });
```
3. Refresh the page and try clicking on select2,

## Expected behavior and actual behavior

When I follow those steps, I see...
the drop-down is rendered correctly but whatever you do it never opens the drop-down when you click on it 
I was expecting...
i expect the drop-down to be opened correctly 

The issue has been [previously reported](https://stackoverflow.com/questions/23038301/select2-not-working-in-jquery-steps) for the jquery.steps.js plugin and the workaround seems to be calling the select2 after the jquery.steps init script and then everything works fine
## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:v3.2.1
- yii2-widget-select2 version: v2.1.3 

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by buttflattery** [comment]
up

**Comment by kartik-v** [comment]
This seems to be an issue when using select2 plugin with another plugin. 

Not sure what needs to be done in this extension to resolve (do you have any suggestions). It seems that you would need to program your app and JS code accordingly as per external plugin needs to ensure the right dependency for your use case.

**Comment by buttflattery** [comment]
Sorry for reopening it as it does not seem to be an issue any more with the latest version of jquery steps plugin `1.1.0` seems more like jquery steps issue rather than select2, i just checked with jquery 3.4.1 and select2 `dev-master dd09e46 ` it works ok 
![image](https://user-images.githubusercontent.com/1536454/58584866-bbc97180-8270-11e9-8aab-b714c1163fde.png)
