### ISSUE TITLE
CSS issue with GridView after 2.0 upgrade

### ISSUE THREAD

**Issue by darkalor** [kartik-v/yii2-widget-select2#28]
After updating to the 2.0 version, when using Select2 with GridView it defaults to "display: table", so width does not scale with it's contents.
![clipboard01](https://cloud.githubusercontent.com/assets/2834813/7552021/3aea3b52-f6a7-11e4-88d5-d7b93a5fb5e9.png)

Only happens with THEME_KRAJEE and THEME_BOOTSTRAP.

**Comment by kartik-v** [comment]
Not sure what is expected. Can you explain?

I see the Select2 rendering fine on [the grid demo page](http://demos.krajee.com/grid-demo). Check the author filter.

**Comment by philippfrenzel** [comment]
I have the issue the other way round, size is "maximized" as you'll use krajee theme and otherwise "minimized" -> only in grid as filter!

![screenshot 2015-05-10 06 57 22](https://cloud.githubusercontent.com/assets/2319890/7553104/df52247c-f6e1-11e4-8aea-07c46971e548.png)

**Comment by kartik-v** [comment]
As mentioned in my previous comment - the Select2 widget will scale to the table column width for the above two themes. You need to provide the column width (e.g. the `width` property in `kartik\grid\DataColumn`) to set a fixed size for the column so that you have a consistent width.

Else if you are not happy, the new Select2 widget also allows you to use other themes or your own new themes.

**Comment by darkalor** [comment]
It just seems like strange default behavior. At the moment it scales down to the point that it cuts off text and breaks the "clear" button. The previous version did not do this. Additionally, this is inconsistent to how the default textinput filters behave - they seem to have some minimal size + padding.

Here's a slightly more better example of what I got after upgrading (all three dropdowns actually have something selected):
![clipboard01](https://cloud.githubusercontent.com/assets/2834813/7553313/f5188824-f6f9-11e4-951c-2abff876659f.png)


Also, there seems to be an issue with the "clear" button for the other themes as well:
![clipboard02](https://cloud.githubusercontent.com/assets/2834813/7553305/711913ae-f6f9-11e4-87af-5ffdf0628261.png)

**Comment by kartik-v** [comment]
IMO... looking at the above screenshots... I think this should be better addressed in the design of your UI - how you want the various inputs to appear -- and what input types you must choose.

The Role or Status column for example is so small in width-- whatever input type you choose (including a native SELECT or TEXT) - will not be readable by the user.

I may for example be considering a checkbox as a filter for Status if the width is so narrow. Alternatively, for other inputs where i need a larger width I would force a fixed width column and make the table enclosed in BS responsive container so it horizontally scrolls... just suggestions - but there are many ways to address the above.

**Comment by darkalor** [comment]
> The Role or Status column for example is so small in width-- whatever input type you choose (including a native SELECT or TEXT) - will not be readable by the user.
My point was that this happens with the updated select2 widget only. With version 1.0 of the widget or with a default textbox the column's width would be the same as others (i.e. it is not supposed to be so narrow)

Either way, no point discussing this anymore if that's the intended behavior.
Thank you for the suggestion though. Checkbox is sadly not an option as those are not binary choices, but I will consider using a bootstrap container.

**Comment by kartik-v** [comment]
I have enhanced the widget a bit to ensure this works better and will push the updated version.
