### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by Dilden** [kartik-v/yii2-widget-select2#283]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [X] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. visit http://demos.krajee.com/widget-details/select2#usage-templates
2. enter "<script>alert('xss vuln');</script>
3. see alert dialogs

## Expected behavior and actual behavior

When I follow those steps, I see...

JS alert dialogs, revealing XSS vulnerabilities

I was expecting...

to not have XSS vulnerabilites

## Environment

Browsers

- [ ] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Expect to happen across all systems

Libraries

- jQuery version:
- yii2-widget-select2 version:

## Isolating the problem

- [X] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [ ] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
It is an [issue with the source plugin](https://github.com/select2/select2/issues/4587) and needs to be fixed there

**Comment by Dilden** [comment]
I suspected it was something with Select2 rather than the Yii2 wrapper. Nevertheless, it was present on the demos page and this was the only way I knew of to disclose the vulnerability to you. Thanks for your work.
