### ISSUE TITLE
Default width for Bootstrap 4

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-widget-select2#284]
The select 2 field is not displayed / aligned correctly as other form fields (label on top of input field):
![select2](https://user-images.githubusercontent.com/9432804/60647403-fed6c000-9e80-11e9-8247-592af8a4cdef.png)

On further investigation, the default width is set to 'auto' in code in [line 223](https://github.com/kartik-v/yii2-widget-select2/blob/master/src/Select2.php#L223), any reason why 100% is not used? (Have tested changing that to 100% and the field is aligned correctly).

There's workaround by updating width in pluginOptions, but is there a way to set the default globally if changing this is not possible?

Have tested with V2.1.3 and dev-master.

**Comment by kartik-v** [comment]
Actually this is needed for input group addons to work correctly in Bootstrap 4... will update this with a fix.
