### ISSUE TITLE
Lost registration of Select2KrajeeAsset when using custom theme in widget

### ISSUE THREAD

**Issue by SHI1989** [kartik-v/yii2-widget-select2#292]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Add a select2 with customTheme
2.
3.

## Expected behavior and actual behavior

When I configure a select2 widget with other theme which is not of krajee theme, Select2KrajeeAsset is not being registered and this causes an js error if you are using some of the extended functionality from select2. In my case is the appears the error below:

> Uncaught ReferenceError: initS2Loading is not defined

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- yii2-widget-select2 version:

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Not sure I can reproduce an issue here. You can check how you are loading assets on your page and if the asset bundles are loading as intended - else explicitly load the asset bundles on your view if needed. Ensure the dependencies to asset bundles are also correctly configured and loaded.
