### ISSUE TITLE
Filtered Select All

### ISSUE THREAD

**Issue by alexforte** [kartik-v/yii2-widget-select2#295]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Try to search/filterd for a Value with mutiple results
2. Try to Select All 
3. All values are returned rather then ONLY search/filterd values

## Expected behavior and actual behavior

When i search/filter for values, i.e. ROME, i want to click on Select All to select all searched/filtered values i.e. ROME 1, ROME 2, ecc...

Actually Select All return all values and NOT all searched/filtered values
## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [x] Mobile

Libraries

- jQuery version:
- yii2-widget-select2 version: latest

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Will be resolved by #301
