### ISSUE TITLE
Limit height for multiple select and customize each option

### ISSUE THREAD

**Issue by ykrasnoborodikova** [kartik-v/yii2-widget-select2#297]
Hello!
1. Is it possible to set the maximum height setting for select?
Like a `<select style="height: 1em;">...</select>`
If the selected options do not fit, then just do not show them.
2. Is it possible to configure styles/classes for each element?
Like a:
```
<select>
<option style="color: white" value=1>white</option>
<option style="color: black" value=2>black</option>
<option class="custom_class_orange" value=3>orange</option>
</select>
```

**Comment by kartik-v** [comment]
You need to use the select2 source plugin's formatting methods to achieve this. For example, you need to use `templateResult` within `pluginOptions` to configure the rendering of how each of the dropdown options are rendered. 

Refer the [advanced usage demo](https://demos.krajee.com/widget-details/select2#usage-advanced) and [select 2 plugin docs](https://select2.org/dropdown#templating).
