### ISSUE TITLE
One problem in IE

### ISSUE THREAD

**Issue by githubjeka** [kartik-v/yii2-widget-select2#30]
After last update all `Select2` widgets is open always in IE.

![image](https://cloud.githubusercontent.com/assets/874234/7559948/a33c7c68-f7c6-11e4-8ba4-6b07ca6530f0.png)

And it can not be closed.

In other browsers, such problems are not noticed.

**Comment by githubjeka** [comment]
P.S.

Via `Select2::widget` - works correctly
Via  `$form->field($model, 'status')->widget(Select2::classname(), ...` - always open in IE

**Comment by kartik-v** [comment]
Your issue cannot be replicated. You may need to check if you have other javascript or broken code on your site causing the issue.

The [Demo page](http://demos.krajee.com/widget-details/select2) contains various Select2 widgets which all render fine on ALL IE versions IE8 to IE 11 - including SUPPORT for the OLD OBSOLETE IE8.

Check the first example in the [basic usage section](http://demos.krajee.com/widget-details/select2#usage-basic) - it includes a Select2 rendered via ActiveForm.

**Comment by disasterovich** [comment]
same problem in ie 11

**Comment by kartik-v** [comment]
The issue you mention cannot be reproduced. You need to check your page for other conflicting javascript or CSS that maybe causing this.

You may want to [check the single and multiple selects on the demo page](http://demos.krajee.com/widget-details/select2#usage-sizes) and update.

**Comment by disasterovich** [comment]
Something strange, but it happens when placeholder value contains cyrillic symbols, like
```php
'placeholder' => 'Все типы',
```
when
```php
'placeholder' => 'All type,
```
all is well

**Comment by vilkh3m** [comment]
@disasterovich confirm this problem show when placeholder got some polish letters "żółąćś" :( onle on IE
