### ISSUE TITLE
Empty field with Ajax and multiple send string

### ISSUE THREAD

**Issue by omsi668** [kartik-v/yii2-widget-select2#304]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [X] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
Hello,

When I updated the plugin from 2.1.4 to 2.1.6 I have a bunch of fields not working anymore and can't find a proper solution to it (I then expect it's a bug). 
The context is a page with 3 Select2 plugins, all optional, all with multiple and Ajax. Everything was working fine with 2.1.4.

This is the code of one of them :

`Select2::widget([
        'data'          => $skills,
        'options'       => [
            'multiple'    => true,
            'class'       => 'form-control',
        ],
        'model' => $searchModel,
        'attribute' => 'skills',
        'pluginOptions' => [
            'minimumInputLength' => 2,
            'ajax'               => [
                'url'            => Yii::$app->urlManager->createUrl(['/ajax/find-skill']),
                'processResults' => new JsExpression(AjaxController::processResultsFindJs()),
            ],
            'language'           => [
                'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
            ],
        ],
    ]);`

$skills is populated with an array of preselected values if you come to the form already populated.

This form will populate a searchFilter where $skills is declared as an attribute of searchFilter as public $skills = [];

No specific rules are set to skills attribute except "safe"

Then we populate the skills attribute of the searchFilter with the load() method. (I wrote everything but in the end this is just classic search, no extra JS, no fancy method)

The problem is that, if I don't fill any skill in my search, select2 will still send an empty string, and then populate the field with an empty token (see attachment).
![empty_token](https://user-images.githubusercontent.com/17141323/68407403-cbd07000-0183-11ea-86ab-60886b25d471.png)

How to avoid that?

Thank you

Libraries

- jQuery version: 3.4.1
- yii2-widget-select2 version: 2.1.6

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by phrakon** [comment]
The similar issue after update: multiple=>false + ajax: can't preset value by initValueText while pluginOptions['placeholder'] exists. that placeholder should be dropped at all or
`` 'placeholder' => !$model->gallery_id ? 'Select item...' : null,``
Anyway something has been broken...

**Comment by kartik-v** [comment]
Check if it is resolved with the above fix. Else will reopen.

**Comment by kartik-v** [comment]
Check if it is resolved with the above fix? Else will reopen.

**Comment by kartik-v** [comment]
Check if it is resolved with the latest fix? Else will reopen.

**Comment by phrakon** [comment]
Seems it works.

**Comment by omsi668** [comment]
Hello,

I tried the master branch and the bugs seems to be still there (i still see empty placeholders)

**Comment by kartik-v** [comment]
@omsi668 can you please share your configuration and code sample to reproduce your issue? Currently cannot reproduce your use case.

**Comment by kartik-v** [comment]
I pushed in a small update...

@omsi668 can you please share your configuration and code sample to reproduce your issue? Currently cannot reproduce your use case. 

- Check what is the actual `data` property setting in `Select2` widget for your use case - is it empty, has values or what is it when you see the issue above?
- What is your `placeholder` setting?
- What is the output HTML for the SELECT tag in your browser console?
- Confirm you are running the latest code of Select2 extension from DEV master

**Comment by omsi668** [comment]
Hello,

With this latest fix it seems to work, i don't manage to make it bug again thank you.

Just for information if you want to build a test case i'll still answer your questions as much as possible :

- This is my 'data' property. Problem was that $searchModel->skills contains an entry with an empty string
$skills = [];
if (is_array($searchModel->skills)) {
    foreach ($searchModel->skills as $skillId) {
        $skills[$skillId] = Skills::findOne($skillId)->getLabel();
    }
}
- No placeholder setting
- Select2 Html : 
`
<select id="matching-skills" class="form-control select2-hidden-accessible" name="Matching[skills][]" multiple="" size="4" data-s2-options="s2options_c4acac00" data-krajee-select2="select2_bcacd2b6" style="width: 1px; height: 1px; visibility: hidden;" data-select2-id="matching-skills" tabindex="-1" aria-hidden="true">

</select>
<span class="select2 select2-container select2-container--krajee select2-container--below" dir="ltr" data-select2-id="2" style="width: 100%;"><span class="selection"><span class="select2-selection select2-selection--multiple" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="-1" aria-disabled="false"><ul class="select2-selection__rendered"><li class="select2-search select2-search--inline"><input class="select2-search__field" type="search" tabindex="0" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" role="searchbox" aria-autocomplete="list" placeholder="" style="width: 0.75em;"></li></ul></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>`

- This is obviously with dev-master 58d9a32

Thank you
