### ISSUE TITLE
Select options is empty via Ajax

### ISSUE THREAD

**Issue by loveorigami** [kartik-v/yii2-widget-select2#307]
After update to v 2.1.6 ajax calls not populate option

v. 2.1.4 - works fine!
![2019-11-20_12-10-54](https://user-images.githubusercontent.com/98164/69225450-7d619f00-0b8f-11ea-98b1-33ba24f4c26c.jpg)

v. 2.1.6 - select options is empty
![2019-11-20_12-09-15](https://user-images.githubusercontent.com/98164/69225540-a1bd7b80-0b8f-11ea-8f78-478acd247736.jpg)

Select2 config
```php
        return [
            'initValueText' => $val, // set the initial display text
            'options' => [
                ['placeholder' => 'Select...'],
                'id' => $this->fieldId,
            ],
            'pluginOptions' => [
                'allowClear' => true,
                'placeholder' => [
                    'id' => '',
                    'placeholder' => 'Select...'
                ],
                'minimumInputLength' => 2,
                'ajax' => [
                    'url' => $this->getLoadUrl(), // here ajax url
                    'dataType' => 'json',
                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                ],
                'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                'templateResult' => new JsExpression('function(data) { return data.text; }'),
                'templateSelection' => new JsExpression('function (data) { return data.text; }'),
            ],
        ];
```

==============
Browsers

- [* ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [* ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3
- yii2-widget-select2 version: 2.1.4 and 2.1.6

**Comment by uktamovdilshod** [comment]
You must remove ['placeholder' => 'Select...'], line

**Comment by loveorigami** [comment]
Thanks! It is work!
