### ISSUE TITLE
Select2 2.0.0 doesn't work in modal demo

### ISSUE THREAD

**Issue by akorinek** [kartik-v/yii2-widget-select2#31]
When you look at your demo that uses the modal dialog, you will see that the search box is not responsive and the search does not work. I've seen the problem appear in my code after updating to 2.0.0

**Comment by kartik-v** [comment]
You must remove modal's `tabindex` attribute property for Select2 to render properly. Check this [again on the demo site in the advanced usage section](http://demos.krajee.com/widget-details/select2#usage-advanced).

**Comment by balakrishnan178** [comment]
Awesome it's working properly sir , really help to us.

Modal::begin([
    'options' => [
        'id' => 'kartik-modal',
        'tabindex' => false **# // important for Select2 to work properly**
    ],
    'header' => '<h4 style="margin:0; padding:0">Select2 Inside Modal</h4>',
    'toggleButton' => ['label' => 'Show Modal', 'class' => 'btn btn-lg btn-primary'],
]);
echo Select2::widget([
    'name' => 'state_40',
    'data' => $data,
    'options' => ['placeholder' => 'Select a state ...'],
    'pluginOptions' => [
        'allowClear' => true
    ],
]);
Modal::end();
