### ISSUE TITLE
Validation error problem

### ISSUE THREAD

**Issue by monbang** [kartik-v/yii2-widget-select2#315]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [ x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [ x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Install package with composer  "kartik-v/yii2-widget-select2" version: "dev-master"
2. Install package with composer "yiisoft-bootstrap4" version: "2.0.8"
3. Add Active form with required field and submit form.

## Expected behavior and actual behavior

When I follow those steps, I see...
![localhost_8080_daily-entry_create](https://user-images.githubusercontent.com/57852225/72058439-1aba9300-32f6-11ea-976b-1022d3e1a3ec.png)

I was expecting...
![localhost_8080_daily-entry_create (2)](https://user-images.githubusercontent.com/57852225/72058630-6e2ce100-32f6-11ea-83cd-8388a03bf47e.png)

## Environment

Browsers

- [X ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ X] Linux
- [ ] Mobile

Libraries

- jQuery version: v3.4.1
- select2/select2: 4.0.12
- yii2-widget-select2 version: dev-master (ref: 9203ffbfaca0b47082fbee2d2840ae28f53818e8)
-kartik-v/yii2-krajee-base: v2.0.5

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

--- the "css/select2-krajee-bs4.css"

has the following code 
`/**
 * Bootstrap validation states
 */
.has-error.select2-container--krajee-bs4 .select2-dropdown,
.has-error .select2-container--krajee-bs4 .select2-selection {
    border-color: #dc3545;
}

.has-error .select2-container--open .select2-selection,
.has-error .select2-container--krajee-bs4.select2-container--focus .select2-selection {
    box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25);
    border-color: #dc3545;
}`

but the bootstrap4 has not has-error class for validation it has is-valid and is-invalid class
after form validation is run on server side the empty required fields has html:-
```<div class="form-group field-dailyentry-account_id required validating" data-select2-id="4">
<label for="dailyentry-account_id">Account</label>
<select id="dailyentry-account_id" class="form-control select2-hidden-accessible is-invalid" name="DailyEntry[account_id]" aria-required="true" data-s2-options="s2options_e9bc2761" data-krajee-select2="select2_cc69e73a" style="width: 1px; height: 1px; visibility: hidden;" data-select2-id="dailyentry-account_id" tabindex="-1" aria-hidden="true" aria-invalid="true">
<option value="" data-select2-id="2">Select member...</option>
<option value="61" data-select2-id="7">33, saving, demo 0</option>
<option value="62" data-select2-id="8">L 1, loan, demo 1</option>
</select><span class="select2 select2-container select2-container--krajee-bs4 select2-container--below" dir="ltr" data-select2-id="1" style="width: auto;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-dailyentry-account_id-container"><span class="select2-selection__rendered" id="select2-dailyentry-account_id-container" role="textbox" aria-readonly="true"><span class="select2-selection__placeholder">Select member...</span></span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>

<div class="invalid-feedback">Account ID cannot be blank.</div>
</div>```

I tried adding custom css rule to target the border color of the field but has no idea how to use the .is-invalid class assigned to `select id="dailyentry-account_id"` to change the border color of the select2 generated `span class="select2 select2-container select2-container--krajee-bs4 select2-container--below" ` element

**Comment by dhruba-git** [comment]
temporary fix the issue with adjacent sibling combinator(https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator)
```
select.is-invalid + .select2-container--krajee-bs4 .select2-selection--single {
        border-color: #dc3545;
    }
    select.is-valid + .select2-container--krajee-bs4 .select2-selection--single {
        border-color: #28a745;
    }
```

**Comment by kartik-v** [comment]
I do not think this is required - the plugin already includes the styling for `has-error` and `has-success` states.... 

Check the [basic usage demo no. 1](https://demos.krajee.com/widget-details/select2#usage-basic) - try selecting and unselecting a value to get a `has-error` style and select a valid value to get a `has-success` style.

**Comment by rafaelvaloto** [comment]
I had this problem with the class is-invalid bs4 with yii2-money and yii2-number, the solution I found to solve was to add a JS

`    $(document).on('afterValidateAttribute', function (event, attribute, messages) {
        if (messages.length) {
            $('#' + attribute.id + '-disp').addClass('is-invalid');
        } else {
            $('#' + attribute.id + '-disp').removeClass('is-invalid');
        }
    });`

**Comment by NLeone** [comment]
> I do not think this is required - the plugin already includes the styling for `has-error` and `has-success` states....
> 
> Check the [basic usage demo no. 1](https://demos.krajee.com/widget-details/select2#usage-basic) - try selecting and unselecting a value to get a `has-error` style and select a valid value to get a `has-success` style.

Estimated! I add to the problem, actually I understand that it has the has-error and has-success classes, but how can these classes be implemented when bootstrap4 automatically sets is-valid or is-invalid in the form inputs.

Please beyond the example you show, which I have already reviewed many times, explain to me if you are as kind as I can do to make these styles look correctly.

Thanks a lot! Greetings!

**Comment by NLeone** [comment]
> temporary fix the issue with adjacent sibling combinator(https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator)
> 
> ```
> select.is-invalid + .select2-container--krajee-bs4 .select2-selection--single {
>         border-color: #dc3545;
>     }
>     select.is-valid + .select2-container--krajee-bs4 .select2-selection--single {
>         border-color: #28a745;
>     }
> ```

This is excellent temporary fix! Thanks!
