### ISSUE TITLE
Exclude Select2Asset

### ISSUE THREAD

**Issue by zertex** [kartik-v/yii2-widget-select2#318]
May I use this widget without registration Select2Asset (css not need)?

A use
```
'assetManager' => [
		    'bundles' => [
			    'kartik\select2\Select2Asset' => [
				    'bsDependencyEnabled' => false,
				    'css' => [],
			    ],
		    ],
	    ],
```
but in html:
```
<link href="/assets/f4ec87e1/css/select2-addl.css" rel="stylesheet">
<link href="/assets/f4ec87e1/css/select2-krajee-bs4.css" rel="stylesheet">
```

**Comment by kartik-v** [comment]
Need to check. But specific to Select2, suggest if you can create your own theme css for select 2 and configure that as the `theme` property in your Select2 widget config.

**Comment by kartik-v** [comment]
Need to check. But specific to Select2, suggest if you can create your own theme css for select 2 and configure that as the `theme` property in your Select2 widget config.

For example, if you need to use this with AdminLTE theme - then set just the theme property to `Select::KRAJEE_DEFAULT` which will help you use AdminLTE theme for Select2.

**Comment by zertex** [comment]
```
\kartik\select2\ThemeKrajeeBs4Asset::class => [
				    'css' => [],
			    ],
```
