### ISSUE TITLE
The names of existing items disappear when choosing a new one.

### ISSUE THREAD

**Issue by AScarj** [kartik-v/yii2-widget-select2#320]
Hello. My settings. Multiple = true, ajax
When editing a record, I already have several selected items.
When I want to add another position, the old positions lose their names. Instead of names they have their id
Before adding a position, existing names are displayed normally

![error1](https://user-images.githubusercontent.com/30417116/80860599-1e499f80-8c82-11ea-8d10-4a93837b654a.PNG)
![error2](https://user-images.githubusercontent.com/30417116/80860597-1d187280-8c82-11ea-9afb-74a61e2ba99c.PNG)
![error3](https://user-images.githubusercontent.com/30417116/80860600-1ee23600-8c82-11ea-94bf-d8575ecae714.PNG)

**Comment by AScarj** [comment]
![image](https://user-images.githubusercontent.com/30417116/80907457-c027c580-8d30-11ea-9739-c06b3761ec97.png)
This is where the data that the widget takes for reinsertion is stored. No names are stored in this place, only id

**Comment by gb5256** [comment]
@AScarj I think I have just opened a similar case. Did you find a solution to your issue?
