### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by Djagannath** [kartik-v/yii2-widget-select2#324]
![Снимок экрана 2020-07-10 в 4 10 27 ПП](https://user-images.githubusercontent.com/22425146/87158269-23514d80-c2c8-11ea-9fb3-7e6f1ba912f9.png)
![Снимок экрана 2020-07-10 в 4 09 34 ПП](https://user-images.githubusercontent.com/22425146/87158285-2a785b80-c2c8-11ea-81a2-797a66f54234.png)
![Снимок экрана 2020-07-10 в 4 10 10 ПП](https://user-images.githubusercontent.com/22425146/87158299-3106d300-c2c8-11ea-9fce-bc49f5796f6e.png)
Dump code
![Снимок экрана 2020-07-10 в 4 09 45 ПП](https://user-images.githubusercontent.com/22425146/87158420-61e70800-c2c8-11ea-976f-e3337b64af09.png)

vendor/kartik-v/yii2-krajee-base/src/BootstrapTrait.php
Check this part of code 
    /**
     * Configures the bootstrap version settings
     * @return string the bootstrap lib parsed version number
     */
    protected function configureBsVersion()
    {
        $v = empty($this->bsVersion) ? ArrayHelper::getValue(Yii::$app->params, 'bsVersion', '3') : $this->bsVersion;
        $ver = static::parseVer($v);
        $this->_isBs4 = $ver === '4';
        return $ver;
    }
$this->_isBs4 = $ver === '4';  // result 1

**Comment by kartik-v** [comment]
You may need to check your code - it can be any other Krajee Widget or Extension as well - like the `ActiveForm` where you need to set the `bsVersion`. It is recommended if you can set the `bsVersion` globally to `4` for your use case within `params.php` of your yii2 configuration which can be read via `Yii::$app->params`. This should resolve any other Krajee extension being used also use the same bootstrap version. Check [docs on setting this](https://demos.krajee.com/widget-details/select2#global-bs-version).
