### ISSUE TITLE
Allowclear not working for bootstrap 4 please help! no X icon

### ISSUE THREAD

**Issue by niyozbek** [kartik-v/yii2-widget-select2#327]
is everyone having same issue? there is no X icon to cancel the selected element

**Comment by nathanramli** [comment]
I have the same issue and i use boostrap 3. 
Its seems like because we use the latest update.

**Comment by nathanramli** [comment]
If you are in hurry, just downgrade it immediately to [v2.1.7](https://github.com/kartik-v/yii2-widget-select2/releases/tag/v2.1.7)

**Comment by niyozbek** [comment]
thanks!

**Comment by metola** [comment]
Next release v2.1.9 its ok, if you want last change with bugfix:
`
"kartik-v/yii2-widget-select2": "dev-master#1f095abdc7e319792871eec24c11e9d6eba097c3"
`
