### ISSUE TITLE
allowClear option does not displays clear button at 2.18 version

### ISSUE THREAD

**Issue by cesarcgfg** [kartik-v/yii2-widget-select2#329]
Hi!

## Steps to reproduce the issue

1.Upgrade  kartik-v /yii2-widget-select2  to 2.18
2. add 'pluginOptions' => ['allowClear' => true],  to Select2 Widget

## Expected behavior

The clear button 'x' to be displayed  after selecting an item on select2 dropdown

## Actual behavior

The clear button 'x' is not displayed  after selecting an item on select2 dropdown

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox

Operating System

- [x] Linux

Libraries
- yii2-widget-select2 version: 2.18

## Isolating the problem

After doing composer update noticed that kartik select2 widget is updated from 2.17 to 2.18. After this, the clear buttons is not shown. If rollback  composer.lock and downgrade to kartik select2 widget 2.17, the clear button is displayed as expected.

Regards

**Comment by jozes** [comment]
I have the same issue. I found a workaround in version 2.18 by setting another theme:

'theme' => Select2::THEME_BOOTSTRAP,
'pluginOptions' => ['allowClear' => true],

With THEME_BOOTSTRAP the functionality of allowClear is working as supposed.

**Comment by jozes** [comment]
Hi,
Thanks for your help. 
I followed your instructions and deleted all assets. It is still not working. Maybe the problem lies in the fact that I am using AdminLte template for the application. Besides this there is no other difference. Interesting that it works with previous version normal and works also normal if I only change select2-krajee.css file with the file from previous version.

**Comment by cesarcgfg** [comment]
Hi, 
I deleted all assets too, still not working.
I can reproduce this issue in the both projects that I am working on right now. Same happens on kartik gridview filters.
Forgot to mention that I have only tested with BS4.

params.php:
`<?php
return [
    'bsVersion' => '4.x',
];
`
Grid:
`                        [
                            'class' => 'kartik\grid\DataColumn',
                            'attribute' => 'transport_type_id',
                            'value' => 'transportType.transport_type',
                            'filter' => $transportTypeList,
                            'filterType' => GridView::FILTER_SELECT2,
                            'filterWidgetOptions' => [
                                'options' => ['placeholder' => ''],
                                'pluginOptions' => ['allowClear' => true],
                            ]
                        ],`


Form:
`            <?= $form->field($model, 'transport_type_id')->widget(Select2::class, [
                'data' => $transportTypeList,
                'options' => ['placeholder' => Yii::t('app', '- Choose -')],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]); ?>`

The problem occurs only with the krajee themes:
- Select2::THEME_KRAJEE
- Select2::THEME_KRAJEE_BS4

Best Regards

**Comment by cesarcgfg** [comment]
Hi,
I deleted all assets, is still not working. I can reproduce this issue in the both projects that I am working on right now. As @jozes  says you can avoid this by setting another theme, KRAJEE theme are the ones with the problem:
- Select2::THEME_KRAJEE_BS4
- Select2::THEME_KRAJEE

Forgot to mention that I am working with BS4.
`
            <?= $form->field($model, 'transport_type_id')->widget(Select2::class, [
                'data' => $transportTypeList,
                'options' => ['placeholder' => Yii::t('app', '- Choose -')],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]); ?>
`

Best Regards

**Comment by kartik-v** [comment]
I am not able to reproduce the issue. As @jozes mentioned - can you check if you have any other conflicting CSS library to take care of. It may help if you can share that. One way to check is what has changed from 2.1,7 - there is not much drastic changed on the SELECT KRAJEE BOOTSTRAP 4 version (select2-krajee-bs4.css) --- you can check below

https://github.com/kartik-v/yii2-widget-select2/compare/v2.1.7...master

**Comment by devaptas** [comment]
I found a solution adding this css (plugin css's are setting position: relative):
```
.select2-container .select2-selection--single .select2-selection__clear {
    position: absolute;
}
```

**Comment by canreo** [comment]
> I found a solution adding this css (plugin css's are setting position: relative):
> 
> ```
> .select2-container .select2-selection--single .select2-selection__clear {
>     position: absolute;
> }
> ```

This fixed it for me.  In my case, I specified the "krajee" container and centered it vertically and moved it to the left a bit: 

```
.select2-container--krajee .select2-selection--single .select2-selection__clear {
    right: 2rem;
    top: 6px;
    position: absolute;
}
```

**Comment by metola** [comment]
Hi, me too.
I prefer go to 2.1.7, for the moment.

**Comment by kartik-v** [comment]
Have pushed an update - let know if this fixes your issues - and will reopen if needed.

**Comment by metola** [comment]
Hi Kartik, 

The last change in this commit no work for bs3.
You only change 
-src/assets/css/select2-krajee-bs4.css
and need change in
-src/assets/css/select2-krajee.css

with @devaptas code in select2-krajee.css work well

**Comment by kartik-v** [comment]
Both BS3 and BS4 are updated

**Comment by metola** [comment]
Thanks Kartik, this is.

**Comment by Sensetivity** [comment]
Please,  make a release!
