### ISSUE TITLE
Select All doesn't select elements which values contains minus '-'

### ISSUE THREAD

**Issue by deferenty** [kartik-v/yii2-widget-select2#330]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
There are two similar closed issues: [306](https://github.com/kartik-v/yii2-widget-select2/issues/306) and [312](https://github.com/kartik-v/yii2-widget-select2/issues/312). But the issue still exists.

- [x] The issue still exists against the latest `master` branch of yii2-widget-select2. (version 2.1.9)
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Run the widget
`echo Select2::widget([
    'name' => 'state_10',
    'data' => [
        'first'=>'One', 
        'second' => 'Two', 
        'thi-rd' => 'Three', 
        'fourth-' => 'Four'],
    'options' => [
        'placeholder' => 'Select provinces ...',
        'multiple' => true
    ],
]);
`
## Expected behavior and actual behavior

When press 'Select all' - expecting behavior - select all options.

If some options' values have minus '-', 'Select All' doesn't select them. In the following example only 'One' and 'Two' will be selected. Even so, 'Three' and 'Four' can be selected manually one by one.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- yii2-widget-select2 version:

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

## Workaround
Maybe [this](https://github.com/Manu311/yii2-widget-select2/commit/69441892275e5154349d266d6db2935f4a96e155) can help to resolve the issue - change 46 row of 'select2-krajee.js':

from `val = $(this).attr('id').split('-').pop();`
to `[, val] = $(this).attr('id').match(/^select2-[^-]*-result-.{4}-(.*)$/);`

**Comment by deferenty** [comment]
Hello!

Thanks for such a quick hot-fix.

Now everything works fine for the case without active-form and model. 

But if we use active-form and model - Select All stops working, because regex doesn't match any id. It's because with active form and model is formed like `select2-modelName-fieldName-result-randomValue-id`

Maybe regex should be changed to something like this `^select2-\S*-result-.{4}-(.*)$`

**Comment by kartik-v** [comment]
I am not sure the regex will work effectively - and may fail if the fieldName is `result` - I am thinking of using a simple split function to solve this... will update. It will work as long as your value does not match this string: `-result-`
