### ISSUE TITLE
Select2 with Ajax shows id instead of text

### ISSUE THREAD

**Issue by gb5256** [kartik-v/yii2-widget-select2#333]
Hi,

You can see the problem on kartik's own demo page as well.
As you see in this screenshot, the first entry shows the ID, not the text.
Seems to be with a values that are already set on page load.
Values that are added afterwards (and whose data comes via AJAX) are fine (as seen in the example below MANDI).

Besides this, even if you unselect the 1030 tag (and not reload the page) and then reselect the same value from the filtered list, it will still display 1030 and not the name selected.

I do not know if this is an issue with this extension or with Select2 itself.

![image](https://user-images.githubusercontent.com/324658/106398492-59485180-6413-11eb-92b0-21fb82ddcef4.png)
Any help highly appreciated.

gb5256

**Comment by kartik-v** [comment]
No this is the initial saved data array which has to be set to show the names correctly. It is been corrected in the demos. Have a look.

```php
[
   'data' => $yourInitialSavedList, // id => name key value pairs
   // other settings
]
```

**Comment by uzkurama** [comment]
> No this is the initial saved data array which has to be set to show the names correctly. It is been corrected in the demos. Have a look.
> 
> ```
> [
>    'data' => $yourInitialSavedList, // id => name key value pairs
>    // other settings
> ]
> ```

what about passing another data (options) for templateResult, I need to get array as id, text, status (for set color for items), but your data structure does not allow to do it
