### ISSUE TITLE
Theme for Bootstrap 5 Floating Label

### ISSUE THREAD

**Issue by nhatzbulawan** [kartik-v/yii2-widget-select2#339]
1. Set the bootstrap version to 5 through params
2. Set the Active Form to Floating Label
3. Add the Select2 Widget

![image](https://user-images.githubusercontent.com/3007744/134897139-b84696de-e0cd-496b-ab16-0ac373225a55.png)

**Comment by kartik-v** [comment]
Enhancement done (note that floating labels will not be styled differently for INPUT LARGE or SMALL).

Refer the [updated demo for floating labels (BS5.x only)](https://demos.krajee.com/widget-details/select2#usage-floating )

**Comment by nhatzbulawan** [comment]
Doesn't work as well for other widgets such as Date Picker and File Input.

**Comment by nhatzbulawan** [comment]
The update does not reflect in kartik-v/yii2-widgets repo. I am only using the bundle repo. 

Thank you so much for your effort and contribution to the community.
