### ISSUE TITLE
Multiple select

### ISSUE THREAD

**Issue by klevron** [kartik-v/yii2-widget-select2#34]
Hello

Actually it is not possible to handle multiple select since this widget do not handle array as input value : 

```php
<?= Select2::widget([
    'name' => 'test',
    'value' => [1],
    'data' => [1=>'Test 1', 2=>'Test 2'],
    'pluginOptions' => [
        'multiple' => true,
    ],
]); ?>
```
=> *Illegal offset type* at https://github.com/kartik-v/yii2-widget-select2/blob/master/Select2.php#L122

PS: Thanks for your work, your widgets are really useful.

**Comment by kartik-v** [comment]
Set `options['multiple']` to `true` instead of `pluginOptions['multiple']` and confirm if it works.

If so will update the docs.

**Comment by klevron** [comment]
It will do the same (illegal offset type)

**Comment by makroxyz** [comment]
I did this as workaround in Select2.php line 122
```php
$multiple = ArrayHelper::getValue($this->options, 'multiple', false);
 if ($multiple) {
    $key = empty($this->value) ? [] : $this->value;
    $val = empty($this->initValueText) ? [] : $this->initValueText;
    $this->data = array_combine($key, $val);
} else {
    $key = empty($this->value) ? '' : $this->value;
    $val = empty($this->initValueText) ? $key : $this->initValueText;
    $this->data = [$key => $val];
}
```

**Comment by kartik-v** [comment]
You need to set the value array keys correctly... 

For example if you need to have values 1 and 2 preselected:

Instead of setting:  `'value' => [1, 2]`

you need to set it up as  `value => [1 => 1, 2 => 2]`

**Comment by kartik-v** [comment]
Ok will check this and update

**Comment by kartik-v** [comment]
@makroxyz will check your feedback and update... however I understand your use case is more applicable when the `initValueText` setting is been set.

**Comment by makroxyz** [comment]
I don't understand your last commit.
It  doesn't solve the issue.

I have keys array from my model, and initValueText is an array which contains "descriptions".    $this->data = [$key => $val] will always fail!

Could you explain me how to do, please?

**Comment by kartik-v** [comment]
Are you talking about multiple selections using ajax?

**Comment by makroxyz** [comment]
Yes I am

**Comment by kartik-v** [comment]
Ok - I will update on that separately... I understand this issue was more about normal multiple select.

**Comment by amujagtap21** [comment]
my select2 widget work perfectly but not allowed me to select option from list plz help me to solve this problem. 
<?php 
$homeurl= Yii::$app->getUrlManager()->getBaseUrl();
$url = \yii\helpers\Url::to(['getartistlist']);
$initScript = <<< SCRIPT
  function (element, callback) {
    var id=\$(element).val();
    if (id!=="") {
       // alert('id not null' + id);
      \$.ajax("{$url}&id=" + id, {
        dataType: "json"
      }).done(function(data) { callback(data.results);});
    }
  }
SCRIPT;
            ?>
            <?= select2::widget([
          'name'=>'aaa',
          'pluginOptions'=>[
          'escapeMarkup' => new JsExpression("function(m) { return m; }"),
            'ajax' => [
              'url' => $url,
              'dataType' => 'json',
              'data' => new JsExpression('function(term,page) { return {search:term}; }'),
            'results' => new JsExpression('function(data,page) { return {results:data.results};}')
            ],
            'initSelection' => new JsExpression($initScript)

          ]
    ]); ?>
