### ISSUE TITLE
Search not auto focusing in jQuery 3.6.0

### ISSUE THREAD

**Issue by rinu** [kartik-v/yii2-widget-select2#343]
This is a duplicate of https://github.com/select2/select2/issues/5993

I completely understand that it's not this project's problem and should be solved in select2/select2. However that project has not been maintained properly for over a year and it's not certain what's going to happen.

Would you consider locking the jQuery version for this project? It would look something like `"bower-asset/jquery": "<=3.5.*"` in `composer.json`. I have done that for my own project as a temporary fix.

**Comment by kartik-v** [comment]
Fixed via above commit (yes this is a jquery/plugin specific issue - however have provided a fix here).
