### ISSUE TITLE
Style out of place after update to V2.2.3

### ISSUE THREAD

**Issue by cwongwpp** [kartik-v/yii2-widget-select2#346]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Create a multi select field in view:
```
$data = ['aaaa', 'bbbb', 'cccc (very long very long)', 'dddd (very long text)'];
echo $form->field($model, 'field1')->widget(Select2::classname(), [ 
        'data' => array_combine($data, $data),
        'options' => [
            'placeholder' => 'Select...',
            'multiple' => true,
        ],
    ]);
```

## Expected behavior and actual behavior

When I follow those steps, I see...
Selected items aren't aligned to left:
![screenshot01](https://user-images.githubusercontent.com/100173136/157182240-b8db31db-4566-414a-b03a-63bce73db58d.png)
When selected items have long text, only 1 is shown, the other one is hidden:
![screenshot02](https://user-images.githubusercontent.com/100173136/157182305-958e0573-819f-4447-a6b5-8f852c3e5788.png)

I was expecting...
(downgrade to V2.2.2)
![screenshot-222-01](https://user-images.githubusercontent.com/100173136/157182211-6dca1440-09c1-4bd7-b56b-e7c4804717f9.png)
![screenshot-222-02](https://user-images.githubusercontent.com/100173136/157182222-df59e91d-1405-4fc9-adee-fea137a1067b.png)

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.6.0
- yii2-widget-select2 version: 2.2.3
- Yii2 version: 2.0.45
- Bootstrap 4.6.1

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by thtmorais** [comment]
I have this problem too.

**Comment by SegaSh99** [comment]
I have this problem too

**Comment by kartik-v** [comment]
Cannot reproduce your issue - seems you are using MULTIPLE select feature. [Cross check the demos page](https://demos.krajee.com/widget-details/select2#usage-sizes) for multiple selection where it works fine. You may want to check if you are not having a caching issue on your environment running outdated/stale assets.  After update to a new select2 release, clean up web runtime cache and runtime assets and also your browser cache and retry,

**Comment by cwongwpp** [comment]
While there are no issues from the demo page, this issue is reproducible with a brand new project with just a form. Original tests were done on Chrome, I have now tested on Safari and Firefox as well - no issue with V2.2.2 but same issue with V2.2.3 across these browsers. Runtime assets and caches and browser caches were cleared after updating the lib.

**Comment by thtmorais** [comment]
https://github.com/kartik-v/yii2-widget-select2/issues/346#issuecomment-1081109263

Yes, i self has many projects using this extensions, and all projects has this problem. Tryed in Google Chrome and Firefox in Ubuntu 20.04 LTS.

**Comment by sniper888** [comment]
the demo page work Select2 4.1.0-rc.0, but the composer download Select2 4.0.13
(composer.json "kartik-v/yii2-widget-select2": "@dev", )

I have this problem too
I use bs4.x multiple feature with allowClear option
