### ISSUE TITLE
Release 2.2.4

### ISSUE THREAD

**Issue by Commifreak** [kartik-v/yii2-widget-select2#352]
https://github.com/kartik-v/yii2-widget-select2/commit/2346248bb09377bd4f0a585d7cad10be103d72ca#r78192702

This is a real blocker, since release 2.2.3 introduced the 1px BS3 bug.

When do you plan to release 2.2.4?

**Comment by kartik-v** [comment]
Done.

**Comment by Commifreak** [comment]
❤️
