### ISSUE TITLE
Calling unknown method: kartik\select2\Select2Asset::addLanguage()

### ISSUE THREAD

**Issue by matnatalis** [kartik-v/yii2-widget-select2#38]
Hello Kartik
Thanks for this useful widget
I am getting this error whenever I try to use the widget

Calling unknown method: kartik\select2\Select2Asset::addLanguage()

**Comment by kartik-v** [comment]
You need to ensure you have updated all your packages via composer. This extension depends on **yii2-krajee-base** and you must ensure you have the updated version of that.

**Comment by matnatalis** [comment]
Thanks Kartik this has worked.

Before doing the update, version 1.0.0 was working fine all higher version were giving the same error

**Comment by kartik-v** [comment]
You should not face such issues unless you are manually copying files to install. You must auto update via composer to avoid issues like this because of dependencies.

**Comment by ganesh002** [comment]
Hi Kartik i have also same problem for select2 widget 
i have update the package also but till didn't solve
Help please.
