### ISSUE TITLE
array_combine() expects parameter 1 to be array, string given

### ISSUE THREAD

**Issue by timmy78** [kartik-v/yii2-widget-select2#39]
Hi
Before [this commit](https://github.com/kartik-v/yii2-widget-select2/commit/2ee7a85e8f0e4c92e95652ceec059072d21f438d) it was working.

The error message : "array_combine() expects parameter 1 to be array, string given".
The file : kartik-v\yii2-widget-select2\Select2.php at [line 133](https://github.com/kartik-v/yii2-widget-select2/commit/2ee7a85e8f0e4c92e95652ceec059072d21f438d#diff-b986b5d88da9a2a05c951595521a2a2cL123)

My code : 
```
//$data = 'keyword1,keyword2,keyword3'
$form->field($model, 'keywords')->widget(Select2::className(), [
    'pluginOptions' => [
        'tags' => true,
    ],
    'options' => [
        'multiple' => true
    ]
])
```

```$model->keywords``` contains a string, not an array.
And the input is not filled anymore with the values.

Thanks

**Comment by kartik-v** [comment]
It is expected and correct. You have `options['multiple']` set to `true`, in that case the value must be an array. So you must convert your value to an array for such cases - OR - do not use `options['multiple']` if you have a single string value.

**Comment by timmy78** [comment]
I have a string like "keyword1,keyword2,keyword3".
Still not working, the initial values are not set.

```
$form->field($model, 'keywords')->widget(Select2::className(), [
    'pluginOptions' => [
        'tags' => true,
    ],
    'data' => [...]
])
```

So I will stop using Select2 and I will use TagsInput :(

**Comment by kartik-v** [comment]
Not sure what's the problem for your use case? As I said, your value must be an array for the `multiple`. 

You are definitely setting some configuration wrongly (NOTE the difference with Select2 latest release compared to earlier). Try these sample codes below and it should work:

Let's assume you want 2 of 3 values preselected.

### WITHOUT MODEL
```php
echo Select2::widget([
    'name' => 'kv',
    'pluginOptions' => [
        'tags' => true,
    ],
    'data' => [1=>'keyword1', 2=>'keyword2', 3=>'keyword3'],  
    'value' => [1, 2]  // NOTE THIS IS AN ARRAY of keys above
]);
```

### WITH MODEL & ACTIVE FORM
You should set the model attribute value to the same value


```php
$model->keywords = [1, 2];  // NOTE THIS IS AN ARRAY of keys
$form->field($model, 'keywords')->widget(Select2::className(), [
    'pluginOptions' => [
        'tags' => true,
    ],
     'data' => [1=>'keyword1', 2=>'keyword2', 3=>'keyword3'],  
])
````

**Comment by timmy78** [comment]
Yes I understand that the attribute "keywords" need to be an array. But before the update it could be a string with commas and it worked perfectly.

So I updated my code and I have now an array...

**Comment by samiek** [comment]
I am working on an update function for  and using select2 widget but am getting this error array_combine() expects parameter 1 to be array, integer given what could be wrong
my update function is as follows

`public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        $task_user=TaskUser::findOne(['task_id'=>$model->task_id]);
        if(!$task_user){
            throw new NotFoundHttpException("The task has no assigned member(s).");
        }

        if ($model->load(Yii::$app->request->post()) && $task_user->load(Yii::$app->request->post())){ 
             $model->save();
                       
            $name=$data['TaskUser']['assigned_to'];
            //$model->link('assignedUser',$_POST['TaskUser']['assigned_to'],[]);
            foreach ($name as $key => $value) {
               $t=new TaskUser();
               $t->task_id=$model->task_id;
               $t->assigned_to=$value;
               $t->assign_type=$_POST['Task']['assign_type'];
               $t->created_by=yii::$app->user->id;
               $t->team_id=$_POST['TaskUser']['team_id'];
              $ta[]= $t->save();
            }
            return $this->redirect(['view', 'id' => $model->task_id]);
        } else {
            return $this->render('update', [
                'model' => $model,'task_user'=>$task_user
            ]);
        }
    }

and my update form`
$url = \yii\helpers\Url::to(['userslist']);
`echo $form->field($task_user,'assigned_to')->widget(\kartik\widgets\Select2::classname(),[
    
    'model'=>$task_user,
        'options'=>['placeholder'=>'choose...',],
    'pluginOptions'=>['allowClear'=>true,'multiple'=>true,'tags'=>true,
    'ajax'=> [
        'url' => $url,
        'dataType' => 'json',
        'data' => new JsExpression('function(params) {return {q:params.term}; }'),
       // 'processResults' => new JsExpression($resultsJs),
        'cache' => true,
        'delay' => 250,
    ],
    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
    'templateResult' => new JsExpression('function(users) { return users.text; }'),
    'templateSelection' => new JsExpression('function (users) { return users.text; }'),
    ],
    ])->label('Assign Users');

?>`

kindly help am stuck and a bit new to kartik widget
thank you
