### ISSUE TITLE
JS error on clear

### ISSUE THREAD

**Issue by RomeroMsk** [kartik-v/yii2-widget-select2#42]
When clicking on clear button JS error will appear:
```
Uncaught TypeError: Cannot set property 'prevented' of undefined
```
You can reproduce it in demos page.

**Comment by kartik-v** [comment]
This is [related to this issue](https://github.com/select2/select2/issues/3348) on Select2 ... for which I had worked on a temporary fix using Select2 events - will check how to work around this.

**Comment by kartik-v** [comment]
This is [related to this issue](https://github.com/select2/select2/issues/3320) on Select2 ... for which I had worked on a temporary fix using Select2 events - will check how to work around this.

**Comment by kartik-v** [comment]
This is [related to this issue](https://github.com/select2/select2/issues/3320) on Select2 ... for which I had worked on a temporary fix within the `yii2-widget-select2` extension using Select2 events - will check how to work around this based on the progress of the requested change in the plugin.

**Comment by RomeroMsk** [comment]
I think it was too early to update Select2 to 4.0 in your widget. It has so many bugs...

**Comment by kartik-v** [comment]
The widget was upgraded only after the stable release of Select2 plugin v4.0.0.

Bugs in the plugin are not in my control though. 

The previous release can be picked up if you need... although I feel the newer version is more extensible inspite of the bugs.

**Comment by kartik-v** [comment]
The widget was upgraded only after the stable release of Select2 plugin v4.0.0.

Bugs in the plugin are not in my control though. 

The [previous release can be picked up here](https://github.com/kartik-v/yii2-widget-select2/releases/tag/v1.0.1) if you need... although I feel the newer version is more extensible inspite of the bugs.

**Comment by RomeroMsk** [comment]
Of course, it is not in your control, just a thought that it was not stable release at all. Now after `composer update` we can not use your widget because of all these bugs... Will downgrade to previous release.
And yes, of course, 4.0 is much extensible and better, just need some time to fix some stuff :)

**Comment by RomeroMsk** [comment]
Thank you!
