### ISSUE TITLE
Trigger custom event `krajeeselect2:cleared`

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-widget-select2#44]

**Comment by kartik-v** [comment]
Extension of fix #42 to ensure we trap the value of Select2 on clear.

**Comment by emiliobruno** [comment]
Hi Kartik,

After run "composer update" the select2 is no longer worging in my applications. What should I do  ?

Thanks,

Emilio

**Comment by kartik-v** [comment]
Ensure you have updated packages from composer for Select2 includingany dependent extension you are using (e.g. DepDrop, dependent-dropdown etc.).

Its recommended to ensure you remove caching issues. So clean up the web runtime assets folder, the local browser cache and restart and retry.

Anyway, the updated releases work fine on the demo sites just for info.
