### ISSUE TITLE
Removing one option removes all in multiple selection mode

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-widget-select2#45]
In multiple selection mode, when multiple options are selected and one of them removed, all the selected options are removed. This currently occurs with the online examples at http://demos.krajee.com/widget-details/select2#usage-sizes

**Comment by kartik-v** [comment]
This is resolved.

**Comment by YasserHassan** [comment]
Thank you @kartik-v for the fix. Works now.
