### ISSUE TITLE
initSOpen not defined

### ISSUE THREAD

**Issue by esquire900** [kartik-v/yii2-widget-select2#46]
Newest version gives a JS error:

Uncaught ReferenceError: initS2Open is not defined

And leaves the spinning icon hanging, without loading select2

**Comment by kartik-v** [comment]
You have an outdated version - upgrade.

**Comment by pkbhadkoliya** [comment]
Same error coming even after "composer update -v --prefer-dist"
My composer file has following require:
    "php": ">=5.4.0",
    "2amigos/yii2-chartjs-widget": "*",
    "2amigos/yii2-google-maps-library": "*",
    "2amigos/yii2-tinymce-widget": "*",
    "aws/aws-sdk-php": "*",
    "facebook/php-sdk-v4": "*",
    "iron-io/iron_worker": "*",
    "kartik-v/yii2-detail-view": "*",
    "kartik-v/yii2-icons": "*",
    "kartik-v/yii2-social": "*",
    "kartik-v/yii2-widgets": "*",
    "rsr/yii2-button-dropdown-sorter": "*",
    "yiisoft/yii2": "*",
    "yiisoft/yii2-authclient": "*",
    "yiisoft/yii2-bootstrap": "*",
    "yiisoft/yii2-imagine": "*",
    "yiisoft/yii2-swiftmailer": "*"

Do I need to add anything?

**Comment by kartik-v** [comment]
You need to check your composer.json.

- Check your minimum-stability setting. If its set to `stable` then only stable versions will be downloaded. If you set it to `dev` anything latest will be downloaded.
- You have not included versions for your files. At least include "@dev" as described in docs.
-You need to reorder the extensions correctly based on dependencies. Set `yii2-widgets` before `yii2-detail-view` for example.

**Comment by kartik-v** [comment]
You need to check your composer.json.

- Check your minimum-stability setting. If its set to `stable` then only stable versions will be downloaded. If you set it to `dev` anything latest will be downloaded.
- You have not included versions for your packages in require section. At least include "@dev" as described in docs.
- You need to reorder the extensions correctly based on dependencies. Set `yii2-widgets` before `yii2-detail-view` for example.

You may do some reading on composer dependencies. If you are not sure... then an approach you could take is to remove all extension packages from require section except the yii core ones. Then slowly add extensions one by one and see if the latest version is getting uploaded. If not then you may need to reorder them correctly.

**Comment by DishaA** [comment]
hello kartik-v,
I am having the same problem as questioned by esquire900..... can you please tell me how to upgrade to the newer version? 
I'm new to yii2 framework. So please help!
