### ISSUE TITLE
Just curious tagging for single not multiple

### ISSUE THREAD

**Issue by JamesBarnsley** [kartik-v/yii2-widget-select2#49]
Hi,

I was wondering whether it is possible to use tagging for single selection and not multiple.

Say an item does not appear in the search list but I want the user to be able to add his own item. The user can enter in his own item or select from the dropdown. Is this possible with the current select2?

James.

**Comment by kartik-v** [comment]
This is not supported directly by the core plugin and requires custom javascript.

**Comment by kartik-v** [comment]
Yes will include this as an enhancement.
