### ISSUE TITLE
using without bootstarp

### ISSUE THREAD

**Issue by kmaurya125** [kartik-v/yii2-widget-select2#5]
Hi,
I'm using this widget in my project. I'm just curious is it possible to eliminate bootstrap css & js calls in that. I have custom frontend theme and bootstrap's default css & js cannot be used. I don't want to disturb your any of widget.

**Comment by kartik-v** [comment]
You can try doing that by setting your CSS from AssetManager... however note specific styling is offered only by bootstrap css e.g. input-group-addons/buttons, and the error states - for active field etc... (bootstrap is a pre-req for the widget to be rendered correctly) - but if you carefully set each CSS component for your custom style - you may achieve it technically.
