### ISSUE TITLE
Uncaught ReferenceError: initS2Open is not defined

### ISSUE THREAD

**Issue by MohammedAbir** [kartik-v/yii2-widget-select2#50]
When i was update composer after that displaying this error 
initS2Open is not defined

My version is updated .

please give me solution .

I am waiting for your reply.

**Comment by kartik-v** [comment]
If you are sure you have the updated extension... then it seems to be a caching issue at your end.

Whenever you update any extension (with JS & CSS)... ensure you clean up your web-server runtime assets, and then clear your browser cache and restart before you use them.

**Comment by MohammedAbir** [comment]
bro i applied all but its not working

**Comment by manoelt** [comment]
Same here, I am still checking...

**Comment by igokul1973** [comment]
During update of composer due to new plugin installation (nepstor/yii2-datetime-compare-validator), new kartik select2 version (among others) have been installed. All is working fine on my Mac (MAMP), but when I uploaded changes to the LAMP server (Ubuntu Server 14.04), I am having the same issue. All selects are now dead - the system cannot find initS20Open...

**Comment by tcash11** [comment]
Same here, ran a composer update on my local WAMP project and all worked fine, but then when I did it on our production LAMP server it broke all the selects with error: "Uncaught ReferenceError: initS2Open is not defined(anonymous function)" and causing all our selects to just have loading spinners. Any thoughts on a fix? Let me know details I could provide to help debug.

**Comment by kartik-v** [comment]
Folks in this thread. All of you need to set your `composer.json` correctly to ensure you have the right `Select2` version installed. There is clear versioning of for dependent packages being done across extensions to ensure you have the right stable versions.

If you want to debug where you have it wrong, just remove all the packages from the `require` section of your composer.json - except the yii core ones... and slowly add an extension one by one to see where you are putting a wrong dependency.

**Comment by tcash11** [comment]
I was able to fix this actually by clearing the web/assets folder in my production environment, I see you recomended this before my apologies for not trying that first. Updated Selects look great!
