### ISSUE TITLE
Option 'ajax' is not allowed for Select2 when attached to a <select> element.

### ISSUE THREAD

**Issue by TimNZ** [kartik-v/yii2-widget-select2#52]
Ignore

**Comment by kartik-v** [comment]
Not the right place to post this query. You need to post your query about v4.0 changes -- to the Select2 plugin author.

Release 2.x of `yii2-widget-select2` uses the Select2 plugin v4.0.

**Comment by TimNZ** [comment]
Thanks, I quickly removed and closed the issue when I realised it was my mistake.
Problem with doing a composer update and not managing versions, things can quickly get confusing.

Great work, much appreciated.


On 1 July 2015 at 7:19:37 am, Kartik Visweswaran (notifications@github.com) wrote:

Not the right place to post this query. You need to post your query about v4.0 changes -- to the Select2 plugin author.

Release 2.x of yii2-widget-select2 uses the Select2 plugin v4.0.
