### ISSUE TITLE
List with item '0' shows id instead of display value.

### ISSUE THREAD

**Issue by evilito** [kartik-v/yii2-widget-select2#53]
Hello, when using a model to populate a select2, e.g. a table with just id and name fields. If there's one record with name='0', and you select it, the select2 will display the id instead after the selection. It works fine with other records. Can this be fixed? Thank you.

**Comment by kartik-v** [comment]
Resolved via latest commit (upgrade to release v2.0.2).

**Comment by gaurabhi** [comment]
I'm also Getting the same issue and I'm using latest version . 
![zeroin dd](https://user-images.githubusercontent.com/36297855/36030194-3912aa0a-0dcc-11e8-853f-c870ce070218.PNG)
