### ISSUE TITLE
Cannot use multiple tags in Select2 on ActiveForm Model Field

### ISSUE THREAD

**Issue by utdeep** [kartik-v/yii2-widget-select2#55]
I am using the new Select2 extension to allow multiple tags on a field in my form model. I have not been able to determine a way to initialize the field with multiple tags.  Only a single tag appears. This is also important if the form has to be reloaded if there is a validation error with another field.

***Example:***

**FORM MODEL**

    class TestForm extends Model {
        public $tags;
        public function rules(){
                return [['tags', 'required'],];
        }
    }

**CONTROLLER ACTION**

    public function actionTest() {
        $model = new TestForm();
        $model->tags = ['dogcat', 'dog'];
        return $this->render('test', ['model' => $model,]);
    }

**VIEW FILE FORM FIELD**

    //minimal select2 with multiple tags
    field($model, 'tags')
        ->widget(Select2::classname(), [
            'options' => [
                'multiple'=> true,
                ],
            'pluginOptions' => [
                'tokenSeparators' => array(',',' '),
                'tags' => true,
                ]
            ]);?>

This always results in: PHP Warning – yii\base\ErrorException Illegal offset type

**Comment by Leammas** [comment]
Seems to me it's generally up to multiple option, as I am stucked with it not using tags.

**Comment by utdeep** [comment]
I found a way to do this by creating a select2 with this extension using the non-active form method but using the active form field name.  Works like a charm!

**Comment by Leammas** [comment]
Bu the way I occasionaly found it fixed in 2.0.4 (at least for my use case). Probably this one could be closed.

**Comment by utdeep** [comment]
I tried it, but still had problems using the very basic example above.  Are you sure it works?

**Comment by Leammas** [comment]
Well it goes ok for both my and your (on the shot below) use cases.
![ex](https://cloud.githubusercontent.com/assets/9443290/11377050/195f62f6-92f5-11e5-8de7-1525b6dcbb7e.PNG)

Here's the composer.lock piece

```
            "name": "kartik-v/yii2-widget-select2",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/kartik-v/yii2-widget-select2.git",
                "reference": "fa0175d936012eac3f7a382792cbb13948015c4e"
            },
```
