### ISSUE TITLE
Rendering select2 widget within in an Ajax Tab - re initialization error

### ISSUE THREAD

**Issue by matthewdaize** [kartik-v/yii2-widget-select2#56]
I am having an issue with rendering a select2 within an ajax rendered tab. The content loads fine however the select2 model does not re-init as expected. It initializes fine if loaded via normal page-load.

In either render case (renderPartial and renderAjax), I get a javascript error:
```
Uncaught TypeError: this.select2 is not a function
```

Do I need to add Select2 to assets bootstrap or am I re-initializing it wrong?

Controller (I have tried both renderPartial and renderAjax without success)
```
public function actionTab($id, $load)
    {
        $user = UserModel::findOne($id);
        if ($user instanceof UserModel) {
            $html = $this->renderAjax('panes/_' . $load, ['user' => $user]);
            return Json::encode($html);
        } else {
            throw new HttpException(404, 'User Model Not Found');
        }
    }
```

View (rendered via Ajax) [_userlist.php]
```
$tabs[] = [
            'label' => '<i class="fa fa-users"></i> Managed Users',
            'content' => 'Loading Users...',
            'linkOptions' => ['data-url' => Url::to(['client/tab', 'id' => $client->id, 'load' => 'userlist'])]
    ];

<?= TabsX::widget([
    'id' => 'user-tabs',
    'encodeLabels' => false,
    'bordered' => true,
    'items' => $tabs,
    'pluginOptions' => [
        'enableCache' => false,
    ],
    'pluginEvents' => [
        'tabsX.success' => 'function() {
            $("[data-krajee-select2]").each(function(data) {
                this.select2({});
            })
        }',
    ]
]); ?>
```

Thanks!

**Comment by kartik-v** [comment]
The plugin options are not there in your select2 plugin.. you can fetch them as a JS variable stored within `data-krajee-select2`.

**Comment by ttzviiol** [comment]
Hi Kartik,
Didn't really understood your answer.
I too use Select2 inside TabsX, and all Select2 fields shows loading icon forever.
Please advise. thanks!
