### ISSUE TITLE
Get id from selected option in select2 widget

### ISSUE THREAD

**Issue by RGTimothy** [kartik-v/yii2-widget-select2#6]
When we used select2, we would get more than 1 option, then we can select 1 of them. In the process of firebug console, i got json data results such as id & text of all the available options. The question is how can i get the id from the selected option? Thank you.

**Comment by RGTimothy** [comment]
I get the id by adding this code : 
<pre>
....
'pluginEvents' => [
			"change" => 'function(data) { 
				var data_id = data.added["id"];
				alert(data_id);
			}',
		],
</pre>

**Comment by RGTimothy** [comment]
Today I update my select2 widget and got many changes. So this time I got this issue as I couldnt get the data id with my code above since the json has different data and has no "added" value inside. Please help to get the data id as fast as the previous method, sir. Thank you.

**Comment by devlat** [comment]
I have same problem. Anybody solved it?

**Comment by milen-vm** [comment]
You can use jquery to get array of ids for selected items.
`'pluginEvents' => [
            "change" => 'function() { 
                var data_id = $(this).val();
                alert(data_id);
            }',
        ],`

**Comment by devlat** [comment]
milen-vm,
Thank you for response.
