### ISSUE TITLE
Integrate select2 widget inside GridView columns 

### ISSUE THREAD

**Issue by Nasreddine** [kartik-v/yii2-widget-select2#60]
Integrate select2 widget inside GridView columns like it is shown in the demo :
For boolean column I've used 'class' => '\kartik\grid\BooleanColumn', I want to apply it in relational attribute like author ?

![demo]
(http://i.imgur.com/s6J0KRT.png)

Another question about css styling. Do you apply special css ? It seems that my grid style was overridden with the main css.

**Comment by kartik-v** [comment]
You may need to read [GridView documentation](http://demos.krajee.com/grid) and [GridView demos](http://demos.krajee.com/grid-demo) to understand how you setup your grid to use Select2 as a filter. The extensions do use their own CSS via yii asset bundles. You may want to read Yii docs to manage your asset bundle dependencies and/or manage your asset config via yii assetmanager.

**Comment by sketch-dev23** [comment]
# aaa## ###

**Comment by sketch-dev23** [comment]
z
