### ISSUE TITLE
Select2 hidden in Modal

### ISSUE THREAD

**Issue by mbraidy** [kartik-v/yii2-widget-select2#63]
The select2 is hidden when launched from within a Modal.  It shows though outside the Modal.
I checked with Chrome DevTools and it shows that the container div is 0px x 0px.
Can you please help

**Comment by kartik-v** [comment]
Cannot reproduce your case. 

Check the demo page and [example 3 in advanced usage](http://demos.krajee.com/widget-details/select2#usage-advanced) where Select2 is rendered inside a modal.

**Comment by Squarius** [comment]
Its set to display: none; if u use it with ajaxcrud in modal:

![select2](https://cloud.githubusercontent.com/assets/5981582/9971749/8af6b7c8-5e5e-11e5-90c5-efd031af3853.jpg)
