### ISSUE TITLE
Ability to reset Select2 on form reset

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-widget-select2#64]
Default select2 plugin does not reset on form reset. Add ability to reset Select2 on parent form reset. A new boolean property `changeOnReset` is made available which defaults to `true`.

**Comment by Goast252** [comment]
This solution works only for last Select2 dropdown in the form? Or maybe it's error in my code...

**Comment by MR-omid** [comment]
@Goast252 i also same problem...

**Comment by MR-omid** [comment]
this is my solution:  
```
$('#button').click(function(){
        var e=$();
	$('.select2-selection__choice__remove').each(function () {
		e=$(e).add(this);
	})
	for(i=0;i<e.length;i++){
	  setTimeout(function() {
			$('.select2-selection__choice__remove').each(function () {
				this.click()
			})
		},(100*i)) //incremental delay
	}
});
```  
first each collect all select2 option close element, but after remove one of options,select2 trigger change and collection become invalid in DOM.
i use `for` for repeat based on first collection length
in `for` statement use `setTimeout` and `incremental delay time` for waiting change trigger time after every click.
any fix or better solution would be appreciated .
