### ISSUE TITLE
Select2 not loading data when used with kartik\widgets\ActiveForm, kartik\builder\Form and kartik\builder\FormGrid

### ISSUE THREAD

**Issue by possebon** [kartik-v/yii2-widget-select2#65]
Hi,

I used the Select2 with success on ActiveForm base (Yii2).

But when I tried to use in a form where I use the kartik\widgets\ActiveForm, kartik\builder\Form and kartik\builder\FormGrid, the dropdown list is rendered on page but without values.

The code I'm using is this:

       $form = ActiveForm::begin(['type'=>ActiveForm::TYPE_VERTICAL]);

        echo FormGrid::widget([
            'model'=>$model,
            'form'=>$form,
            'autoGenerateColumns'=>true,
            'rows'=>[
                [
                    'contentBefore'=>'<legend class="text-info"><small>'. Yii::t('app','Customer Basic Information') . '</small></legend>',
                    'attributes'=>[       // 2 column layout
                        'customer_name'=>['type'=>Form::INPUT_TEXT, 'options'=>['placeholder'=>Yii::t('app','Enter the Name...')]],
                        'customer_taxid'=>['type'=>Form::INPUT_TEXT, 'options'=>['placeholder'=>Yii::t('app','Enter the Tax ID...')]],
                        'marital_status_marital_status_id'=>['type'=>Form::INPUT_WIDGET, 'widgetClass'=>'kartik\select2\Select2',
                            [
                                'items' => ArrayHelper::map(MaritalStatus::find()->orderBy('marital_status_name')->asArray()->all(), 'marital_status_id', 'marital_status_name'),
                                //'data' => ArrayHelper::map(MaritalStatus::find()->all(),'marital_status_id', 'marital_status_name') ,
                                'options' => ['placeholder' => Yii::t('app','Select a Marital Status')],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ],
                        ],

                    ]
                ],

I already tested the return of ArrayHelper and it does return an array with the values.

**Comment by kartik-v** [comment]
Your configurations are not correct for both Select2 and Form. Read documentation.

Your Form builder configuration is wrong for usage with widget. [Read documentation for Form](http://demos.krajee.com/builder-details/form#settings).If `'type'=>Form::INPUT_WIDGET` then the`options` for each attribute will correspond to the widget settings (and not input options)... if its a normal HTML input it will correspond to input's html `options.

For Select2 there is no `items` property, there is a `data` property. Read [Select2 docs](http://demos.krajee.com/widget-details/select2).
