### ISSUE TITLE
Dropdown is shown above navbar

### ISSUE THREAD

**Issue by RomeroMsk** [kartik-v/yii2-widget-select2#68]
![image](https://cloud.githubusercontent.com/assets/4639951/9933915/f4994d7a-5d56-11e5-8d55-0f8787fae34d.png)
I think we need to play with `z-index` styles to put the dropdown under navbar.

**Comment by RomeroMsk** [comment]
Solution:
Change `z-index` for `.select2-dropdown` to `999` and override it for `.modal-open .select2-dropdown` to `1051` (to not show dropdown under modal).
Ex:
```
.select2-dropdown {
    z-index: 999;
}
.modal-open .select2-dropdown {
    z-index: 1051;
}
```

**Comment by kartik-v** [comment]
Just wondering why should the dropdown not float over navbar? 

How will user enter the input in such case if it is behind the navbar?

**Comment by RomeroMsk** [comment]
It just looks wierd: the input itself is under navbar, but dropdown is above (widget is cut into two parts). Have you ever seen that native select or Bootstarp Dropdown was above navbar? :)
Please, open [demo page](http://demos.krajee.com/widget-details/select2), resize the window height to about 600px, open dropdown of any select and scroll slowly - you will see what I mean.

If page layout doesn't allow user to enter the input because of navbar - it is bad layout. I'm just concerning about situation when you opened dropdown and scrolled the page, so the dropdown is placed above navbar.

**Comment by kartik-v** [comment]
The modal CSS will not work that way because the Select2 dropdown is appended to the body and outside the modal.

I suggest the following fix for this in your CSS....

```css
.your-container .navbar {
    z-index: 1055;
}
```
