### ISSUE TITLE
FR: add ability to select all options

### ISSUE THREAD

**Issue by RomeroMsk** [kartik-v/yii2-widget-select2#69]
Can you add a button/icon and/or hotkey to select all options in multiselect?
When we replaced native `select`s with `Select2`, users are claimed about not working `Ctrl+A` and `Shift+click`.

**Comment by RomeroMsk** [comment]
@kartik-v, any thoughts?

**Comment by kartik-v** [comment]
This will need to be an enhancement. Will consider and incorporate this when I get time... In the interim you could get this done via custom javascript code.

**Comment by RomeroMsk** [comment]
Ok, thanks.

**Comment by RomeroMsk** [comment]
Here is the discussion in Select2 GitHub: https://github.com/select2/select2/issues/195
And here is an example of implementation from kevin-brown: http://jsbin.com/seqonozasu/1/edit?html,js,output

**Comment by kartik-v** [comment]
I have had enhance and do it differently than the suggestion mentioned.

Fixed via update to release v2.0.5. (not yet tagged)

**Comment by kartik-v** [comment]
Refer the [Select2 widget tags demo](http://demos.krajee.com/widget-details/select2#usage-tags) for understanding the usage.

**Comment by RomeroMsk** [comment]
Thanks, man!
