### ISSUE TITLE
Templating to display formatted items

### ISSUE THREAD

**Issue by juanruben** [kartik-v/yii2-widget-select2#71]
Hello Kartik.. I'd like to use formatted items as in the "Ajax & Templates advanced example", but in a Basic of single select widget with model fields. I want to include some detail information from the model as a reference that would help the user to decide the option to choose. Do you have an example that shows how is this possible?

**Comment by kartik-v** [comment]
You may try expanding the templates and the plugin features allowing this in the plugin docs.

If you need generic tips and queries... you may also [post queries on programming help and tips in this new forum here](http://webtips.krajee.com/questions).
