### ISSUE TITLE
Suggested link for better handling of long text

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-widget-select2#72]
http://xcellerant.net/2015/09/17/fixing-the-width-of-a-select-2-with-a-long-value-in-a-bootstrap-form-group-or-input-group/

have applied just width display and table-layout which does the job for me. not sure on effect or necessity of the other attributes. Had this fixed once before in previous version but lost it.

**Comment by designia** [comment]
@andrewblake1 nice job man!
