### ISSUE TITLE
GridView: Input_SELECT2 Widget stretched

### ISSUE THREAD

**Issue by xiandalisay** [kartik-v/yii2-widget-select2#73]
After updating the select2, the widget got stretched even if the width was set. It didn't happened before the update.

![capture](https://cloud.githubusercontent.com/assets/7392803/9988923/1c3b7c12-6087-11e5-9382-b8de14d3bd95.PNG)

**Comment by kartik-v** [comment]
You must set a fixed width for your parent container holding Select2. So in your case change grid columns to have a fixed width (e.g. `200px`) by setting the `width` property for your grid column. The Select2 widget has been updated for the default behavior to stretch to 100% width.

**Comment by xiandalisay** [comment]
I set the widths in every grid column via percentages so that the total width would result to 100%. In the new update, the widths are neglected. Instead the select2 widget is stretched, as you have said.

**Comment by kartik-v** [comment]
Not sure if you have the updated code.

You may check [the GridView Demo](http://demos.krajee.com/grid-demo) where it works fine.
