### ISSUE TITLE
Possible bug or documentation error

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-widget-select2#74]
With data, it seems that array keys do not become options values. You can pass with no keys and it works i.e. sequential numeric keys will work however the option value becomes the text.

 It needs to be:
```
data => [
    ['id' => 'value1', 'text' => 'optiontext1',
    ['id' => 'value2', 'text' => 'optiontext2',
]
```
which can be achieved by adding a call similar to the following into init():
```
    private function fixDataKeys()
    {
        if (isset($this->pluginOptions['data'])) {
            $new = [];

            foreach ($this->pluginOptions['data'] as $key => $value) {
                if ($key !== 'id') {
                    $new[] = ['id' => $key, 'text' => $value];
                }
            }

            if ($new) {
                $this->pluginOptions['data'] = $new;
            }
        }
    }
```

Can create pull request if that is easier but guessing you will want to confirm this for yourself first anyway and solution is pretty simple.

**Comment by kartik-v** [comment]
The `data` property needs to be set at widget level and not within plugin options.

**Comment by andrewblake1** [comment]
http://demos.krajee.com/widget-details/select2
states "The array keys are option values, and the array values are the corresponding option labels"

This is the issue - sorry if I didn't make myself clear.

**Comment by kartik-v** [comment]
The data property is to be set similar to a Yii dropdown list. So the doc is correct. As mentioned data is to be set at widget level and not elsewhere. 
```php
echo Select2:widget([ 
    'data' => [ 
        'key1' => 'val1',
        'key2' => 'val2'
    ]
]);
```

**Comment by andrewblake1** [comment]
Thanks, you are correct. I was accidentally passing data into pluginOptions rather than the widgets options.
