### ISSUE TITLE
Documentation error that will likely cause bugs for users.

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-widget-select2#75]
With data, it seems that array keys do not become options values. You can pass with no keys and it works i.e. sequential numeric keys will work however the option value becomes the text.

 It needs to be:
```
data => [
    ['id' => 'value1', 'text' => 'optiontext1',
    ['id' => 'value2', 'text' => 'optiontext2',
]
```
which can be achieved by adding a call similar to the following into init():
```
    private function fixDataKeys()
    {
        if (isset($this->pluginOptions['data'])) {
            $new = [];

            foreach ($this->pluginOptions['data'] as $key => $value) {
                if ($key !== 'id') {
                    $new[] = ['id' => $key, 'text' => $value];
                }
            }

            if ($new) {
                $this->pluginOptions['data'] = $new;
            }
        }
    }
```

Can create pull request if that is easier but guessing you will want to confirm this for yourself first anyway and solution is pretty simple.

**Comment by kartik-v** [comment]
Duplicate to #74.

The docs are correct. You must pass `data` within the widget property and not within `pluginOptions` as mentioned in #74.
