### ISSUE TITLE
Ajax tooltip over options

### ISSUE THREAD

**Issue by juanruben** [kartik-v/yii2-widget-select2#77]
Hello kartik. Thank you for all your contributions in making our job easier. 
Is there a way to get tooltips over options of a select2 widget with some aditional info requested via ajax?
Any suggestion will be appreciated.

Thank you again

**Comment by kartik-v** [comment]
You can explore the templates properties in the plugin options to achieve this. You may need to read the Select2 plugin docs for details.

If you need generic tips and queries... you may also [post queries on programming help and tips in this new forum here](http://webtips.krajee.com/questions).

**Comment by RosyStephen** [comment]
I tried template option, but can't enable bootstrap  tooltip on list. Tried to enable via events but works only on change event not open or opening event.
