### ISSUE TITLE
Multiselect with active form model giving issue

### ISSUE THREAD

**Issue by shailesh1490** [kartik-v/yii2-widget-select2#78]
When using multi select option as true with the Yii2 activeform model the values are not prepopulating.
the issue I am facing is:

when I am doing this:
        $category->category_id = implode(', ', $data);
it is coming as null selected.

When I pass the value like this:
$category->category_id = 'category1, category3,category4'; nothing is coming.

But when I am passing a single value like: $category->category_id = 'category1';
it is coming category selected, but only one is working at a time.

widget: 
 <?= $form->field($category, 'category_id')->widget(Select2::classname(), [                                                                                                       
                                                    'data' => $category_names,                                                     
                                                    'options' => ['placeholder' => 'Enter category...', 'multiple' => true],
                                                    'pluginOptions' => [
                                                        'category' => true,                                              
                                                    ],
                                                ]); ?>

Please take a look and provide a solution.

**Comment by kartik-v** [comment]
Its very similar to how you would pass a multiselect with default yii dropdownList (as an array).Test a default yii listBox widget (multi select) and use the same configuration to set value and data for select2

**Comment by shailesh1490** [comment]
yeah, resolved this one. I forgot to post a comment.

Thanks for your such a nice widget :)
