### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by heiko87** [kartik-v/yii2-widget-select2#79]
The default values I set are not showing.

```PHP
 <?php
    $categories = [1 => 'test1', 2 => 'test2', 3 => 'test3'];
    $dynamicModel->categories = [2]; // (1)
    $dynamicModel->categories = 2; // (2)
    echo $form->field($dynamicModel, 'categories[]')->widget(Select2::className(), [
        'value' => 2, // (3)
        'data' => $categories,
        'options' => ['placeholder' => Yii::t('app', 'Please select'), 'multiple' => true],
        'theme' => Select2::THEME_BOOTSTRAP,
    ]); ?>
```
None of the three variation's is working :(

I saw the other issue in the yii2-widgets repo but you say it's working there, but it isn't for me.

I installed the latest version with composer.

**Comment by heiko87** [comment]
I figured that it's working this wayne when not using the model-mode. Without the model it's working fine. For me it's ok then but I think it would be nice if this is going to be fixed someday :)

**Comment by kartik-v** [comment]
You need to read the Yii documentation to understand this.

- When using with `model` and `active form` - do not set `value` property - its detected automatically by the widget based on the model attribute value
- When using without `model` - set `value` property.

**Comment by darkphase01** [comment]
How about using select2 with model and multiple options?
For example I have a table for things 
[id => 1, name => chair] 
[id => 2, name => table]

And I also have color table
[id => 1, name => blue]
[id => 2, name => red]
[id => 3, name => yellow]

Which I created a relationship and stored in thing_color table in this manner
[id => 1, thing_id => 1, color_id => 1]
[id => 2, thing_id => 1, color_id => 2]
[id => 3, thing_id => 1, color_id => 3]
[id => 4, thing_id => 2, color_id => 1]
[id => 5, thing_id => 2, color_id => 2]

How can i display the selected values in actionUpdate ?

Thanks!!!

**Comment by Lalo19** [comment]
You can try to declare the value in the options array.

<?php
    $categories = [1 => 'test1', 2 => 'test2', 3 => 'test3'];
    $dynamicModel->categories = [2]; // (1)
    $dynamicModel->categories = 2; // (2)
    echo $form->field($dynamicModel, 'categories[]')->widget(Select2::className(), [
        'data' => $categories,
        'options' => [ 'value' => 2,'placeholder' => Yii::t('app', 'Please select'), 'multiple' => true],
        'theme' => Select2::THEME_BOOTSTRAP,
    ]); ?>

**Comment by darkphase01** [comment]
I was not aware you can put value in options.
Thank you @Lalo19  ^^

**Comment by tranmanhtoan237** [comment]
how can i hold the value of the select box from the last submit to other turn submit, please ?

**Comment by Pkp07** [comment]
> You can try to declare the value in the options array.
> 
> 
> 
> $categories = [1 => 'test1', 2 => 'test2', 3 => 'test3'];
> $dynamicModel->categories = [2]; // (1)
> $dynamicModel->categories = 2; // (2)
> echo $form->field($dynamicModel, 'categories[]')->widget(Select2::className(), [
> 'data' => $categories,
> 'options' => [ 'value' => 2,'placeholder' => Yii::t('app', 'Please select'), 'multiple' => true],
> 'theme' => Select2::THEME_BOOTSTRAP,
> ]); ?>

Your answer for some other question with some other problem actually saved my ass😊✌
