### ISSUE TITLE
select2 doesn't work correctly in Pjax 

### ISSUE THREAD

**Issue by meduza777** [kartik-v/yii2-widget-select2#80]
i have a view with GridView and ActiveForm with select2 together in one pjax container. If i change select2 and submit form,  it work very well - grid updates and select2 value changes via pjax. However if i press backward/forward buttons in browser - select2 container get duplicated... 
My guess is when i receive page, there is a code
<code>...jQuery.when(jQuery('#myselectname').select2(select2_5c89864a)).done(...</code>
that always creates a new select2.. maybe it should first check if a particalar select2 already exists in dom and if exists, then create it from string like in yor comment here https://github.com/kartik-v/yii2-widget-select2/issues/19#issuecomment-81402573 ?

**Comment by kartik-v** [comment]
You can try that and call the plugin `destroy` method and then initialize.

**Comment by 641951363** [comment]
simple solution
```php
Pjax::begin(['enablePushState' => true]);
$this->registerJs("$('.select2').remove();", \yii\web\View::POS_END); 
```
