### ISSUE TITLE
IE10 - placeholder cyrillic symbols - can not be closed

### ISSUE THREAD

**Issue by VitProg** [kartik-v/yii2-widget-select2#81]
Problem in IE10, when placeholder value contains cyrillic symbols, like

`'placeholder' => 'Выберите рубрики',`

`Select2` widget is open always in IE.
And it can not be closed
![default](https://cloud.githubusercontent.com/assets/985434/10418108/4ca78502-705a-11e5-87dc-c2522268682b.PNG)

Via `Select2::widget` - works correctly
Via `$form->field($model, 'status')->widget(Select2::classname(),` ... - always open in IE

In other browsers, such problems are not noticed.

**Comment by kartik-v** [comment]
You may want to Html encode the placeholder and try.
