### ISSUE TITLE
Automatic save field

### ISSUE THREAD

**Issue by dogpampa** [kartik-v/yii2-widget-select2#82]
Please provide an example that demonstrates how to build a model to automatically save with select2;
example:

//.... 
Class TesteRecord extends \yii\db\ActiveRecord
{
    //..............
    public function beforeSave($insert){
	//......
	$this->tags = implode(',',array_unique($this->tags));
    }	
    //..............
    public function afterFind($insert){
	parent::afterFind();
	$this->tags = array_filter(explode(',',$this->tags));
    }	
    //..............
}

This will save you a precise time.

Thank you!

**Comment by kartik-v** [comment]
Cannot probably help with your use case You you may also [post queries on programming help and tips in this new forum here](http://webtips.krajee.com/questions).
