### ISSUE TITLE
Load default values from model

### ISSUE THREAD

**Issue by albertborsos** [kartik-v/yii2-widget-select2#83]
I tried to use tags input with a model on update scenario. If I try it without model it is ok, but with model it is not. Am I missed something? Thanks!

```php
<div class="form-group field-usercms-rules">
    <label class="control-label" for="usercms-rules">Rules</label>
    <?= \kartik\select2\Select2::widget([
        'name' => Html::getInputId($model, 'rules'),
        'value' => $model->getRules(\app\models\UserCms::DATA_TYPE_SELECTED),
        'data' => $model->getRules(\app\models\UserCms::DATA_TYPE_SOURCE),
        'pluginOptions' => [
            'tags' => true,
            'multiple' => true,
            'width' => '100%',
            'tokenSeparators' => [',', '\n'],
        ],
    ]) ?>
    <div class="help-block"></div>
</div>

<?= $form->field($model, 'rules')->widget(\kartik\select2\Select2::className(), [
    'data' => $model->getRules(\app\models\UserCms::DATA_TYPE_SOURCE),
    'pluginOptions' => [
        'tags' => true,
        'multiple' => true,
        'width' => '100%',
        'tokenSeparators' => [',', '\n'],
    ],
]) ?>
``` 
![kepernyofoto 2015-10-14 - 10 52 06](https://cloud.githubusercontent.com/assets/7307145/10479088/30d742d6-7262-11e5-95d7-40a541e99185.png)

**Comment by kartik-v** [comment]
You must debug your code and check your model value. Without looking at the code ... one thing that I can see is that you are using the attribute name `rules` which is a keyword and a built in function for yii models. Also I see that you have a method `getRules` which will conflict with the attribute name `rules`.

**Comment by albertborsos** [comment]
Ok, that was my fault. The `$model->load()` overwritten the values with an empty array.. Thank!
