### ISSUE TITLE
can't push to heroku, empty folder

### ISSUE THREAD

**Issue by oratoran** [kartik-v/yii2-widget-select2#84]
Hey Kartik,

I use your yii2-widget-select2 on a yii2 project and push changes to Heroku

Every file is deploying; there seems no error but when I check folder with heroku bash only vendor/kartik-v/yii2-widget-select2  folder is empty.

It created folder but cant put content.

I use fresh git, fresh composer update, anythign I could do but stuck there, 

can you help urgently plz?

Thx

**Comment by kartik-v** [comment]
You may need to check your application settings and application's composer dependencies. Not much I can help on this - you would need to debug it yourself. Start with a fresh Yii app install and then take it from there.
