### ISSUE TITLE
Select2 doesn't work with AJAX popup forms

### ISSUE THREAD

**Issue by Summer-Sadness** [kartik-v/yii2-widget-select2#86]
Hello, Kartik-v. Thank you for your extention, but one problem cames up.
When I use your plugin with PJAX popup forms or with forms generated by AJAX CRUD generetor it doesn't load at all. 
But if I open form in new tab it works properly.
It seems data not to load in popup.
How to fix it?
Thank you very much.

...
Screenshots
works in new tab
https://drive.google.com/file/d/0B2w5wXQr_NKhd0s2MXFaenRPVmc/view?usp=drivesdk
doesnt work in popup
https://drive.google.com/file/d/0B2w5wXQr_NKhOHdwOVNoN05idEU/view?usp=drivesdk

**Comment by kartik-v** [comment]
You would need to reinitialize the plugin after the markup is overwritten. You can provide the `pjaxContainerId` property in the widget and set it to the ID of the pjax container and the widget will auto reinitialize.

 If you need programming tips and help a new Q & A forum has been created for such use and you can [search and ask for questions/help out there](http://webtips.krajee.com/questions).
