### ISSUE TITLE
Get value into form model

### ISSUE THREAD

**Issue by kingrain94** [kartik-v/yii2-widget-select2#87]
i user this code in view form:
<?=
                $form->field($model, 'receiver[]')->widget(Select2::classname(), [
                    'data' => array(1 => 'messi', 2=> 'ronaldo', 3 => 'neymar'),
                    'language' => 'en',
                    'options' => ['multiple' => true, 'placeholder' => 'To ...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
                ?>

and in controller:
$model = new MessageCreateForm();
        $model->create_at = date('Y-m-d h:i');
        $model->sender_id = \Yii::$app->user->getId();
        $model->status = 0;

        if ($model->load(\Yii::$app->request->post())) {
            var_dump($model->receiver);die;
        }

why value of $model->receiver is NULL???

**Comment by kartik-v** [comment]
Looks like you may need to check your model validation rules to ensure the attribute is safe for massive loading via `model->load` method. 

You may want to debug your code. If you need programming tips and help a new Q & A forum has been created for such use and you can [search and ask for questions/help out there](http://webtips.krajee.com/questions). Request if you can use this repo to report this extension specific bugs and enhancements.
