### ISSUE TITLE
Update to Select2 3.5.3

### ISSUE THREAD

**Issue by nabidefacto** [kartik-v/yii2-widget-select2#88]
Hello,

I found one bug with tags. If you try to type in the same tag, that've already been added, it removes both tags. 
http://select2.github.io/select2/ -  it's fixed here
http://demos.krajee.com/widget-details/select2 - but this bug accure here

I found out that Select2.js version in your widget is old. Could you please updated it, or explain how to do it myself?

Thank you very much!

**Comment by nabidefacto** [comment]
Hm, I'm sorry it seems that problem with https://select2.github.io/examples.html
new version.

**Comment by kartik-v** [comment]
Yes check your release and version (you are using a wrong outdated v3.x of plugin) - this widget is updated for latest select2 v4.x plugin
