### ISSUE TITLE
plaginEvents dont works

### ISSUE THREAD

**Issue by wokster** [kartik-v/yii2-widget-select2#9]
The widget works until I insert 'plaginEvents'. This is my widget:

echo Select2::widget(
                   [
                                    'name' => $fname,
                                    'value' => $fname,
                                    'data' => $fval,
                                    'options' => ['multiple' => true],
                                       'pluginOptions' => [
                                           'allowClear' => true
                                       ],
                                    'plaginEvents' => ['change' => ['function(){alert("change");}']]
                    ]);

This is my Error:

exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: kartik\select2\Select2::plaginEvents' in C:\openserver\OpenServer\domains\prodamgitaru.ru\vendor\yiisoft\yii2\base\Component.php:197

**Comment by kartik-v** [comment]
The message is clear... you are using a wrong property.

Read docs... 

The property is named **pluginEvents**

**Comment by wokster** [comment]
how i can use change event ? please give me an example. I reed docs. but dont understand where my falt

**Comment by wokster** [comment]
That is in your docs:
pluginEvents = [
    "change" => "function() { log("change"); }",
    "select2-open" => "function() { log("open"); }",
    "select2-opening" => "function() { log("select2-opening"); }",
    "select2-close" => "function() { log("close"); }",
    "select2-highlight" => "function() { log("highlight"); }",
    "select2-removing" => "function() { log("removing"); }",
    "select2-removed" => "function() { log("removed"); }",
    "select2-loaded" => "function() { log("loaded"); }",
    "select2-focus" => "function() { log("focus"); }",
    "select2-blur" => "function() { log("blur"); }",
];


it is not working

**Comment by efisiobova** [comment]
Using pluginEvents inside a FormGrid seems not working. 
No messages are showed on the console
What am I doing wrong?
thanks
 
`
echo FormGrid::widget([
    'model' => $model,
    'form' => $form,
	'autoGenerateColumns'=>false,
	'rows'=>[	
		[
		'columns'=>2,
		'attributes' => [
			'tipoOperazione'=>['type'=> Form::INPUT_WIDGET, 'widgetClass'=>'\kartik\widgets\Select2',  
				'options'=>['data'=>$datac,],  
			
 				'pluginEvents' => [
					"change" => "function() { log('change'); }",
					"select2:open" => "function() { log('open'); }",
					"select2:opening" => "function() { log('select2-opening'); }",
					"select2:close" => "function() { log('close'); }",
					"select2:highlight" => "function() { log('highlight'); }",
					"select2:removing" => "function() { log('removing'); }",
					"select2:removed" => "function() { log('removed'); }",
					"select2:loaded" => "function() { log('loaded'); }",
					"select2:focus" => "function() { log('focus'); }",
					"select2:blur" => "function() { log('blur'); }",
				]	 			
				
				], 
			
			'dataOperazione'=>['type'=> Form::INPUT_WIDGET, 
				'widgetClass'=>'kartik\datecontrol\DateControl',
				'options'=>[ 'pluginOptions'=>['autoclose' => true], ],
				'style'=>'width:190px',

				], 
			]
		],	
`

**Comment by tobanature** [comment]
sdd
