### ISSUE TITLE
Readonly vs Disabled?

### ISSUE THREAD

**Issue by alexburpeeblu** [kartik-v/yii2-widget-select2#91]
I'm working with a form trying to switch it over to Select2 to add search functionality. It's been a rocky road, and then I spotted an issue with disabled - one of my variables is an array of 5 questions and they can't be edited after the fact at the time being.. so I disabled them. I was trying to get the same reaction as most Readonly properties.. I was trying to make it unselectable and this works.

BUT - disabled also means that the data doesn't get sent along. That's when I noticed that there was a separate readonly property.. but setting it to true doesn't seem to do anything.

Am I missing something here?

**Comment by gdiazderadaa** [comment]
@alexburpeeblu would be helpful to know how you sorted that out, as I'm facing the same problem right now. Thanks

**Comment by kartik-v** [comment]
The [reason for this is this](http://stackoverflow.com/questions/368813/html-form-readonly-select-tag-input)... you can work around it by rendering a hidden input with same NAME and value and getting its data via post.

**Comment by kartik-v** [comment]
Check this [comment on select2 plugin](https://github.com/select2/select2/issues/3387#issuecomment-104961591) as to why the readonly property has been removed in Select2 plugin v4.0 and higher?

**Comment by kartik-v** [comment]
The [reason for this behavior is here](http://stackoverflow.com/questions/368813/html-form-readonly-select-tag-input)... you can work around it by rendering a hidden input with same NAME and value and getting its data via post.

Check this [comment on select2 plugin repo](https://github.com/select2/select2/issues/3387#issuecomment-104961591) as to why the readonly property has been removed in Select2 plugin v4.0 and higher?

I may try to enhance something in this extension to accomodate this when I get time.

**Comment by gdiazderadaa** [comment]
Thanks @kartik-v, had already went for that workaround!
