### ISSUE TITLE
IE fix for multiple select with placeholder

### ISSUE THREAD

**Issue by JanJan01** [kartik-v/yii2-widget-select2#93]
Hi,

Can you put this fix in the code? i'ts from this issue:
https://github.com/select2/select2/issues/3300

---------------------

"Another fix - seems to do everything, with minimal changes to the Select2 code. Search and everything works well. Just modify the Search.prototype.handleSearch method as below. It's on line ~1870"

var lastSearchInput = "";
Search.prototype.handleSearch = function () {
  this.resizeSearch();
  function isEmptyOrSpaces(str) {
    return str === null || str.match(/^ *$/) !== null;
  }

  if (!this._keyUpPrevented) {
    var input = this.$search.val();
    if (!isEmptyOrSpaces(lastSearchInput) || !isEmptyOrSpaces(input)) {
      lastSearchInput = input;
        this.trigger('query', {
            term: input
        });
    }
  }

  this._keyUpPrevented = false;
};

----------------

Thx!

Jan

**Comment by kartik-v** [comment]
Check if the updated extension and plugin assets as per enhancement #94 resolves it.

**Comment by JanJan01** [comment]
Problem resolved!

Thx!

2015-12-14 15:16 GMT+01:00 Kartik Visweswaran <notifications@github.com>:
