### ISSUE TITLE
Force new line with multi-select?

### ISSUE THREAD

**Issue by alexburpeeblu** [kartik-v/yii2-widget-select2#95]
Kartik,

First off thank you for all of these excellent widgets - they have been a great help.

I was wondering if it was at all possible to alter the way that the 'pills' function. Instead of only moving to a new line when the current one is filled up - could each new item selected have its own line?

Thanks!
Alex

**Comment by kartik-v** [comment]
You can style this with CSS by creating your own theme. Refer select2 documentation and the inbuilt Krajee CSS Theme.

**Comment by alexburpeeblu** [comment]
Thanks kartik! Figured it would be something along those lines, have something working along those lines. Is there also a way to integrate tags with selections that exist already as well? As of right now they act as two separate lists and I would like the order that I select them in to matter.
