### ISSUE TITLE
allowClear not working in GridView even in demo

### ISSUE THREAD

**Issue by KirillRyzhkov** [kartik-v/yii2-widget-select2#96]
You have an error on your demo page with select 2 filter.
When allowClear is set to true with placeholder
<pre>
'filterWidgetOptions'=>[
   'pluginOptions'=>['allowClear'=>true],
],
'filterInputOptions'=>['placeholder'=>'Any author'],
</pre>
Gives an error 
<pre>
The select2('close') method was called on an element that is not using Select2.$.fn.select2 @ select2.full.js:5845
select2.full.js:5853 Uncaught TypeError: Cannot read property 'close' of undefined
</pre>

It happens with 'pjax'=>true and only when you click clear second time. First time works ok.
Is it possible to fix?

**Comment by kartik-v** [comment]
This is probably happening after the update to the new SELECT2 plugin release v4.0.1... will need to check...

**Comment by KirillRyzhkov** [comment]
Ok, thanks, yes I have older version and it works there well.

**Comment by kartik-v** [comment]
Have enhanced this and better than before without the flicker while clearing the select2 selection.

**Comment by KirillRyzhkov** [comment]
Thank you. I run composer update but it says Nothing to install or update. I have stability - stable. Do I need dev stability?

**Comment by KirillRyzhkov** [comment]
I am sorry but it did not work for me. I removed kartik-widgets. Installed them again, removed all the assets generated by Yii and still I have this error in the GridView

**Comment by kartik-v** [comment]
Clear you browser cache and web runtime assets and retry...

**Comment by KirillRyzhkov** [comment]
That's weird. I did all this. Still this error.

**Comment by kartik-v** [comment]
Clear you browser cache and web runtime assets and retry... I will tag the release so you can get a stable one via composer soon

**Comment by KirillRyzhkov** [comment]
I cleared browser cache, I removed all generated assets then I access Gridview page, clear second time and this error appears. Select2.php is identical to Github version.

**Comment by kartik-v** [comment]
You can cross check at the demo site... where there is the updated version of this

**Comment by KirillRyzhkov** [comment]
It is working there but not with my grid. That's strange.

**Comment by KirillRyzhkov** [comment]
Somehow true, false not working with allowClear. Even when I have false I have the cross icon and by clicking I get the same error.
<pre>
'filterWidgetOptions'=>[
            		'pluginOptions'=>[
            			'allowClear' => false
            		],
            	],
</pre>

**Comment by KirillRyzhkov** [comment]
It is clear that error is 'pjax'=>true .Because I tried 
<pre>
<?php Pjax::begin(['id' => 'links-grid']) ?>
<?= GridView::widget([
    ]); ?>
<?php Pjax::end() ?>
</pre>

And AllowClear works multiple times.

**Comment by KirillRyzhkov** [comment]
Ok, now after update it works
