### ISSUE TITLE
Multiple select by order selected, not the order that the dropdown is sorted into?

### ISSUE THREAD

**Issue by alexburpeeblu** [kartik-v/yii2-widget-select2#97]
Is this possible? I'm seeing now the application shows multiple selects by placing them in the order that they are sorted inside the dropdown. For instance:

A has a question?
B has a question?
Z has a question?

If I select A, Z and then B I would want to see the selection as:

A has a question?
Z has a question?
B has a question?

But the way that the multiple select works by default it would instead look exactly as it does in the dropdown. Is this modifiable behaviour?

**Comment by kartik-v** [comment]
This is not a inherent plugin feature.

I will incorporate an enhancement specifically for this widget for this.

**Comment by kartik-v** [comment]
Fixed via update to release v2.0.5.

**Comment by kartik-v** [comment]
Note this is not a feature available with the source plugin. Refer #98 and enhancements via release v2.0.5.

There is now a new boolean property `maintainOrder` available in the widget. Set it to `true` to maintain your order.

**Comment by kartik-v** [comment]
Refer the [Select2 widget tags demo](http://demos.krajee.com/widget-details/select2#usage-tags) for understanding the usage.

**Comment by alexburpeeblu** [comment]
Just got back from holiday vacation, excellent fix!
